"""
Norwegian name lists and common-word denylist for PII filtering.

Sources: SSB (Statistics Norway) most-common first/last names (200+ persons),
plus common Norwegian vocabulary used to suppress NER false positives.
"""

# ── Norwegian first names (female) ───────────────────────────────────────────

NORWEGIAN_FEMALE_NAMES: frozenset = frozenset({
    "Aagot", "Aase", "Aashild", "Aasta", "Abigail", "Ada", "Adele", "Adelen",
    "Adelina", "Adriana", "Agata", "Agathe", "Agne", "Agnes", "Agnete", "Agnethe",
    "Agnieszka", "Ågot", "Aida", "Aila", "Aileen", "Ailin", "Aimee", "Aina",
    "Aisha", "Alaa", "Alba", "Aleksandra", "Alette", "Alexandra", "Alfhild", "Alia",
    "Alice", "Alicia", "Alicja", "Alida", "Alina", "Aline", "Alisa", "Alise",
    "Alla", "Alma", "Alona", "Alva", "Alvhild", "Alvilde", "Amal", "Amalia",
    "Amalie", "Amanda", "Amelia", "Amelie", "Amina", "Amira", "Amna", "Amy",
    "Ana", "Anastasia", "Anastasiia", "Anbjørg", "Andrea", "Andreea", "Andrine", "Ane",
    "Aneta", "Anett", "Anette", "Angela", "Angelica", "Angelika", "Angelina", "Anhelina",
    "Anine", "Anisa", "Anita", "Anja", "Anlaug", "Ann", "Ann-Christin", "Ann-Helen",
    "Ann-Karin", "Ann-Kristin", "Ann-Mari", "Anna", "Annabelle", "Annbjørg", "Anne", "Anne-Berit",
    "Anne-Brit", "Anne-Britt", "Anne-Grete", "Anne-Grethe", "Anne-Kari", "Anne-Karin", "Anne-Kristin", "Anne-Lene",
    "Anne-Lise", "Anne-Mari", "Anne-Marie", "Anne-Marit", "Anne-Mette", "Anne-Sofie", "Anneli", "Annelin",
    "Annelise", "Annette", "Anni", "Annie", "Annika", "Anniken", "Annlaug", "Anny",
    "Antonia", "Antonina", "Aria", "Ariana", "Ariel", "Arina", "Arna", "Arnhild",
    "Arya", "Åsa", "Asbjørg", "Åse", "Asha", "Åshild", "Aslaug", "Åslaug",
    "Asma", "Åsne", "Asta", "Åsta", "Astri", "Astrid", "Athena", "Aud",
    "Audhild", "Audny", "Aurelia", "Aurora", "Ausra", "Ava", "Aya", "Ayan",
    "Ayesha", "Ayla", "Aylin", "Ayse", "Azra", "Barbara", "Barbro", "Beata",
    "Beate", "Beathe", "Beatrice", "Belinda", "Bella", "Benedicte", "Benedikte", "Bente",
    "Benthe", "Bergit", "Bergliot", "Bergljot", "Berit", "Berta", "Bertha", "Bertine",
    "Betina", "Bettina", "Betty", "Bianca", "Bibi", "Birgit", "Birgith", "Birgitta",
    "Birgitte", "Birte", "Birthe", "Bjørg", "Bodil", "Borghild", "Borgny", "Bozena",
    "Brit", "Brita", "Brith", "Britt", "Britta", "Brynhild", "Bushra", "Camilla",
    "Carina", "Carine", "Carla", "Carmen", "Carolina", "Caroline", "Cassandra", "Catharina",
    "Catherine", "Cathrin", "Cathrine", "Catrine", "Cecilia", "Cecilie", "Celia", "Celin",
    "Celina", "Celine", "Cesilie", "Charlotte", "Chloe", "Christel", "Christiane", "Christin",
    "Christina", "Christine", "Cicilie", "Cindy", "Clara", "Claudia", "Connie", "Cornelia",
    "Cristina", "Dagfrid", "Dagmar", "Dagny", "Dagrun", "Daiva", "Dalia", "Dana",
    "Daniela", "Daniella", "Danielle", "Danuta", "Daria", "Daryna", "Deborah", "Denise",
    "Desiree", "Diana", "Dina", "Dominika", "Dordi", "Doris", "Dorota", "Dorthe",
    "Dorthea", "Ea", "Ebba", "Edda", "Edel", "Eden", "Edit", "Edita",
    "Edith", "Edle", "Edna", "Edny", "Edyta", "Egle", "Eila", "Eileen",
    "Eilen", "Eilin", "Eir", "Eira", "Eiril", "Eirill", "Eirin", "Eivor",
    "Ekaterina", "Ela", "Elbjørg", "Eldbjørg", "Eldrid", "Elea", "Eleah", "Elen",
    "Elena", "Eleni", "Elfrid", "Eli", "Eliana", "Elida", "Elif", "Elin",
    "Elina", "Eline", "Elinor", "Elisa", "Elisabet", "Elisabeth", "Elise", "Eliza",
    "Elizabeth", "Ella", "Elle", "Ellen", "Elli", "Ellie", "Ellinor", "Elly",
    "Elma", "Elna", "Elsa", "Else", "Else-Marie", "Elsie", "Elvira", "Elzbieta",
    "Ema", "Embla", "Emelie", "Emely", "Emilia", "Emilie", "Emilija", "Emily",
    "Emina", "Emine", "Emma", "Emmeli", "Emmeline", "Emmy", "Enya", "Erica",
    "Erika", "Erle", "Erna", "Ester", "Esther", "Eva", "Evelina", "Eveline",
    "Evelyn", "Evy", "Ewa", "Ewelina", "Fadumo", "Faiza", "Fanny", "Farah",
    "Fatemeh", "Fatima", "Fatma", "Fay", "Felicia", "Fie", "Filippa", "Fiona",
    "Fredrikke", "Freja", "Freya", "Frid", "Frida", "Fride", "Frøya", "Frøydis",
    "Gabija", "Gabriela", "Gabriele", "Gabriella", "Gabrielle", "Galina", "Gerd", "Gerda",
    "Gina", "Gine", "Gintare", "Gitte", "Gjertrud", "Gloria", "Gøril", "Grace",
    "Grazyna", "Greta", "Grete", "Gretha", "Grethe", "Gro", "Gry", "Gudny",
    "Gudrun", "Gudveig", "Gun", "Gunda", "Gunhild", "Gunlaug", "Gunn", "Gunnbjørg",
    "Gunnhild", "Gunnlaug", "Gunnvor", "Gunvor", "Guri", "Guro", "Gyda", "Hafsa",
    "Hailey", "Hala", "Haldis", "Halima", "Halldis", "Halyna", "Hamdi", "Hana",
    "Hanan", "Hanna", "Hannah", "Hanne", "Harriet", "Hatice", "Hedda", "Hedvig",
    "Hege", "Heidi", "Helen", "Helena", "Helene", "Helga", "Helin", "Helle",
    "Hennie", "Henny", "Henriette", "Henrikke", "Herborg", "Herdis", "Hermine", "Hiba",
    "Hild", "Hilda", "Hilde", "Hildegunn", "Hildur", "Hilma", "Hjørdis", "Hodan",
    "Hong", "Huda", "Hulda", "Iben", "Ida", "Idun", "Idunn", "Ieva",
    "Ilona", "Iman", "Ina", "Ine", "Ines", "Inga", "Inge", "Ingebjørg",
    "Ingeborg", "Ingelin", "Inger", "Inger-Johanne", "Inger-Lise", "Inger-Marie", "Ingerid", "Ingfrid",
    "Inghild", "Ingjerd", "Ingri", "Ingrid", "Ingrida", "Ingun", "Ingunn", "Ingvil",
    "Ingvild", "Ingvill", "Inna", "Iqra", "Iren", "Irena", "Irene", "Irina",
    "Iris", "Irma", "Irmelin", "Iryna", "Isa", "Isabel", "Isabell", "Isabella",
    "Isabelle", "Iselin", "Isra", "Iva", "Ivana", "Iwona", "Izabela", "Jacqueline",
    "Jamila", "Jana", "Jane", "Janet", "Janicke", "Janina", "Janita", "Janne",
    "Janniche", "Jannicke", "Jannike", "Jasmin", "Jasmina", "Jasmine", "Jeanett", "Jeanette",
    "Jelena", "Jenni", "Jennie", "Jennifer", "Jenny", "Jessica", "Jette", "Jill",
    "Joan", "Joanna", "Jofrid", "Johanna", "Johanne", "Jolanta", "Jorid", "Jorun",
    "Jorunn", "Josefine", "Josephine", "Judit", "Judith", "Julia", "Juliana", "Juliane",
    "Julianne", "Julie", "Julija", "June", "Juni", "Jurgita", "Justyna", "Kaia",
    "Kaisa", "Kaja", "Kajsa", "Kamila", "Kamile", "Kamilla", "Karen", "Kari",
    "Kari-Anne", "Karianne", "Karin", "Karina", "Karine", "Karla", "Karolina", "Karoline",
    "Karyna", "Katarina", "Katarzyna", "Kate", "Katerina", "Kateryna", "Katharina", "Kathe",
    "Katherine", "Kathinka", "Kathrin", "Kathrine", "Katinka", "Katja", "Katrin", "Katrina",
    "Katrine", "Kaya", "Kelly", "Kerstin", "Khadija", "Kim", "Kine", "Kinga",
    "Kira", "Kirsten", "Kirsti", "Kitty", "Kjellaug", "Kjellfrid", "Kjellrun", "Kjersti",
    "Kjerstin", "Klara", "Klaudia", "Konstanse", "Kornelia", "Kristel", "Kristi", "Kristiane",
    "Kristin", "Kristina", "Kristine", "Krystyna", "Kseniia", "Laila", "Lajla", "Lana",
    "Lara", "Larisa", "Larysa", "Laura", "Layla", "Lea", "Leah", "Leikny",
    "Leila", "Lejla", "Lena", "Lene", "Leni", "Leona", "Leonora", "Lerke",
    "Leyla", "Lia", "Liana", "Lidia", "Lidiia", "Lilian", "Liliana", "Liliia",
    "Lilja", "Lilje", "Lill", "Lilli", "Lillian", "Lilly", "Lily", "Lin",
    "Lina", "Linda", "Lindis", "Line", "Linea", "Linn", "Linnea", "Lisa",
    "Lisbet", "Lisbeth", "Lise", "Liss", "Liubov", "Liudmila", "Liudmyla", "Liv",
    "Liva", "Live", "Livia", "Liz", "Liza", "Lone", "Lorena", "Lotta",
    "Lotte", "Louisa", "Louise", "Lovise", "Lucia", "Lucie", "Lucy", "Luna",
    "Lydia", "Lykke", "Ma", "Madeleine", "Madelen", "Madelene", "Madina", "Magda",
    "Magdalena", "Magna", "Magnhild", "Magni", "Magny", "Maha", "Mai", "Mai-Britt",
    "Maia", "Maida", "Maiken", "Maj", "Maja", "Malak", "Malena", "Malene",
    "Målfrid", "Malgorzata", "Mali", "Malika", "Malin", "Manuela", "Maren", "Margaret",
    "Margareth", "Margarita", "Margit", "Margot", "Margrete", "Margrethe", "Margun", "Margunn",
    "Marharyta", "Mari", "Mari-Ann", "Maria", "Mariam", "Marian", "Mariana", "Mariann",
    "Marianna", "Marianne", "Marie", "Mariel", "Mariell", "Marielle", "Mariia", "Marija",
    "Marika", "Marina", "Marion", "Marit", "Marita", "Marlen", "Marlena", "Marlene",
    "Marry", "Marta", "Marte", "Martha", "Marthe", "Marthine", "Martina", "Martine",
    "Martyna", "Marwa", "Mary", "Mary-Ann", "Maryam", "Maryan", "Maryna", "Marzena",
    "Mathea", "Mathilda", "Mathilde", "Matilda", "Matilde", "Maud", "May", "May-Britt",
    "May-Liss", "Maya", "Maylen", "Medina", "Melanie", "Melina", "Melinda", "Melisa",
    "Melissa", "Merete", "Merethe", "Meryem", "Mette", "Mia", "Michaela", "Michelle",
    "Mie", "Mihaela", "Mikaela", "Mila", "Milana", "Mildrid", "Milena", "Milica",
    "Milla", "Mille", "Millie", "Mimmi", "Mina", "Mira", "Miranda", "Miriam",
    "Mirjam", "Molly", "Mona", "Monica", "Monika", "Møyfrid", "Muna", "My",
    "Nada", "Nadia", "Nadiia", "Nadine", "Nadja", "Naima", "Najma", "Nancy",
    "Nanna", "Naomi", "Nasrin", "Natalia", "Natalie", "Nataliia", "Nataliya", "Natasha",
    "Nathalie", "Nelia", "Nellie", "Nelly", "Ngoc", "Nicole", "Nicoline", "Nikola",
    "Nikoline", "Nina", "Ninni", "Noelle", "Noor", "Nora", "Norah", "Norma",
    "Norunn", "Nour", "Nova", "Oda", "Oddbjørg", "Oddfrid", "Oddlaug", "Oddny",
    "Oddrun", "Oddveig", "Oksana", "Olaug", "Olava", "Olea", "Oleksandra", "Olena",
    "Olga", "Olha", "Oline", "Olivia", "Oliwia", "Othelie", "Othilie", "Otilie",
    "Pamela", "Patricia", "Patrycja", "Paula", "Paulina", "Pauline", "Peggy", "Pernille",
    "Petra", "Phuong", "Pia", "Polina", "Rabia", "Rachel", "Ragna", "Ragne",
    "Ragnhild", "Ragni", "Rahel", "Rahma", "Raisa", "Rakel", "Ramona", "Rana",
    "Randi", "Rania", "Rannveig", "Ranveig", "Rasa", "Rebecca", "Rebecka", "Rebekka",
    "Regina", "Regine", "Reidun", "Reidunn", "Renata", "Renate", "Renathe", "Renee",
    "Rigmor", "Rikke", "Rina", "Rita", "Ronja", "Rønnaug", "Rosa", "Rose",
    "Roza", "Ruby", "Runa", "Rut", "Ruta", "Ruth", "Saba", "Sabina",
    "Sabine", "Sabrina", "Sadia", "Safa", "Safia", "Saga", "Sahar", "Sahra",
    "Saima", "Sally", "Salma", "Samantha", "Samira", "Sana", "Sandra", "Sanja",
    "Sanna", "Sanne", "Sara", "Sarah", "Savannah", "Selam", "Selina", "Seline",
    "Selma", "Senait", "Serina", "Serine", "Sham", "Sharon", "Sheila", "Shirin",
    "Sidra", "Sidsel", "Sienna", "Sigfrid", "Signe", "Signy", "Sigrid", "Sigrun",
    "Sigrunn", "Siham", "Silja", "Silje", "Silvia", "Simona", "Simone", "Sina",
    "Sine", "Siren", "Siri", "Siril", "Sissel", "Siv", "Siw", "Snefrid",
    "Sofia", "Sofie", "Sofiia", "Sofija", "Sol", "Solbjørg", "Solfrid", "Solgunn",
    "Solrun", "Solvår", "Solveig", "Sølvi", "Solvor", "Sonia", "Sonja", "Sophia",
    "Sophie", "Stella", "Stephanie", "Stina", "Stine", "Sumaya", "Sunniva", "Susan",
    "Susann", "Susanna", "Susanne", "Suzanne", "Svanhild", "Svetlana", "Svitlana", "Syeda",
    "Sylvi", "Sylvia", "Sylwia", "Synne", "Synnøve", "Synøve", "Tale", "Tamara",
    "Tania", "Tanja", "Tanya", "Tara", "Tatiana", "Tatjana", "Tea", "Teresa",
    "Terese", "Tetiana", "Thale", "Thanh", "Thea", "Thelma", "Theresa", "Therese",
    "Thi", "Thilde", "Thora", "Thordis", "Thu", "Thuy", "Tia", "Tilda",
    "Tilde", "Tilla", "Tina", "Tine", "Tiril", "Tirill", "Tomine", "Tone",
    "Tonje", "Tora", "Torbjørg", "Tordis", "Torgunn", "Torhild", "Tori", "Toril",
    "Torild", "Torill", "Torun", "Torunn", "Tove", "Trine", "Trine-Lise", "Trude",
    "Turi", "Turid", "Tuva", "Tyra", "Ulla", "Ulrikke", "Una", "Une",
    "Unn", "Unni", "Urszula", "Vaida", "Valborg", "Valentina", "Valentyna", "Valeria",
    "Valeriia", "Vanessa", "Vanja", "Vår", "Vårin", "Vega", "Venche", "Venke",
    "Vera", "Veronica", "Veronika", "Veslemøy", "Vibecke", "Vibeke", "Victoria", "Vida",
    "Vigdis", "Viktoria", "Viktoriia", "Viktorija", "Vilde", "Vilja", "Vilje", "Vilma",
    "Viola", "Violeta", "Vira", "Vita", "Vivi", "Vivian", "Wanja", "Wenche",
    "Wencke", "Wendy", "Wenke", "Weronika", "Wigdis", "Wiktoria", "Wilma", "Wioletta",
    "X", "Yana", "Yara", "Yasmin", "Yelyzaveta", "Yeva", "Yevheniia", "Ylva",
    "Yngvild", "Yordanos", "Yuliia", "Yusra", "Yvonne", "Zahra", "Zainab", "Zara",
    "Zeinab", "Zeynep", "Zlata", "Zoe", "Zofia", "Zuzanna",
})

# ── Norwegian first names (male) ─────────────────────────────────────────────

NORWEGIAN_MALE_NAMES: frozenset = frozenset({
    "Aage", "Aaron", "Aasmund", "Abbas", "Abdallah", "Abdi", "Abdirahman", "Abdul",
    "Abdulkadir", "Abdullah", "Abdullahi", "Abdulrahman", "Abel", "Abraham", "Adam", "Adel",
    "Adem", "Adil", "Adnan", "Ådne", "Adrian", "Åge", "Agnar", "Ahmad",
    "Ahmed", "Ahmet", "Aiden", "Ailo", "Akram", "Aksel", "Alaa", "Alan",
    "Albert", "Albin", "Alejandro", "Aleksandar", "Aleksander", "Aleksandr", "Aleksandrs", "Alex",
    "Alexander", "Alexandru", "Alf", "Alfred", "Ali", "Allan", "Alv", "Alvar",
    "Alvin", "Amanuel", "Amar", "Amer", "Amin", "Amir", "Ammar", "Amund",
    "Anas", "Anatolii", "Anders", "Andre", "Andreas", "Andrei", "Andrej", "Andres",
    "Andrew", "Andrii", "Andris", "Andrius", "Andrzej", "Angel", "Annar", "Ansgar",
    "Anthony", "Anton", "Antoni", "Antonio", "Anwar", "Aram", "Are", "Ari",
    "Arian", "Arild", "Arkadiusz", "Arman", "Armin", "Arn", "Arne", "Arnfinn",
    "Arnljot", "Arnold", "Arnstein", "Arnt", "Arnulf", "Aron", "Artem", "Arthur",
    "Artur", "Arturas", "Arunas", "Arve", "Arvid", "Arvin", "Arvydas", "Aryan",
    "Asad", "Asbjørn", "Asgeir", "Ask", "Aslak", "Asle", "Asmund", "Åsmund",
    "Atlas", "Atle", "Audrius", "Audun", "August", "Aurimas", "Axel", "Ayman",
    "Ayub", "Aziz", "Baard", "Balder", "Bård", "Bartlomiej", "Bartosz", "Bastian",
    "Ben", "Bendik", "Bengt", "Benjamin", "Benny", "Bent", "Bernard", "Bernhard",
    "Bernt", "Bertil", "Bilal", "Birger", "Birk", "Bjarne", "Bjarte", "Bjørge",
    "Bjørn", "Bjørn-Erik", "Bjørnar", "Bo", "Bogdan", "Boguslaw", "Bohdan", "Borgar",
    "Børge", "Boris", "Børre", "Brage", "Brede", "Brian", "Bror", "Bruno",
    "Brynjar", "Brynjulf", "Carl", "Carlos", "Carsten", "Casper", "Caspian", "Cato",
    "Cezary", "Charles", "Charlie", "Chris", "Christen", "Christer", "Christian", "Christoffer",
    "Christopher", "Claes", "Claus", "Colin", "Conrad", "Constantin", "Cornelius", "Cristian",
    "Dag", "Dagfinn", "Dainius", "Damian", "Damir", "Dan", "Dani", "Danial",
    "Daniel", "Daniil", "Danny", "Danylo", "Darius", "Dariusz", "David", "Davyd",
    "Dawid", "Dawit", "Deividas", "Dejan", "Denis", "Dennis", "Denys", "Didrik",
    "Diego", "Dmytro", "Dominic", "Dominik", "Donatas", "Dovydas", "Dragan", "Dylan",
    "Ebbe", "Eddie", "Edgar", "Edgaras", "Edin", "Edmund", "Eduard", "Eduardo",
    "Edvard", "Edvin", "Edvinas", "Edward", "Edwin", "Egidijus", "Egil", "Eigil",
    "Eik", "Eilert", "Eilev", "Eilif", "Einar", "Eirik", "Eivind", "Eldar",
    "Eliah", "Elian", "Elias", "Elling", "Elliot", "Elvin", "Emanuel", "Emil",
    "Emilian", "Emilio", "Emir", "Emmanuel", "Emre", "Emrik", "Endre", "Enes",
    "Eric", "Erik", "Erland", "Erlend", "Erling", "Ernst", "Esben", "Eskil",
    "Eskild", "Espen", "Esten", "Ethan", "Evald", "Evaldas", "Evan", "Even",
    "Eystein", "Eyvind", "Fabian", "Faisal", "Falk", "Farhad", "Felix", "Ferdinand",
    "Fernando", "Filip", "Fillip", "Finn", "Flemming", "Florian", "Florin", "Francis",
    "Francisco", "Franciszek", "Frank", "Frans", "Fred", "Freddy", "Frederik", "Fredrick",
    "Fredrik", "Fridtjof", "Frikk", "Frithjof", "Frits", "Fritz", "Frode", "Gabriel",
    "Gard", "Gaute", "Gediminas", "Geir", "Georg", "George", "Georgios", "Gerhard",
    "Gert", "Gheorghe", "Giedrius", "Gintaras", "Gisle", "Gjermund", "Gjert", "Glen",
    "Glenn", "Goran", "Gøran", "Gorm", "Grzegorz", "Gudbrand", "Gudmund", "Gunnar",
    "Gunvald", "Gustav", "Guttorm", "Haakon", "Haavard", "Hadi", "Håkon", "Haldor",
    "Halfdan", "Hallgeir", "Hallstein", "Hallvard", "Halvard", "Halvor", "Hamid", "Hamza",
    "Hans", "Hans-Petter", "Harald", "Haris", "Harry", "Hasan", "Hassan", "Hauk",
    "Håvar", "Håvard", "Heine", "Helge", "Helmer", "Henning", "Henri", "Henrik",
    "Henry", "Henryk", "Herman", "Hermann", "Hermod", "Hilmar", "Hjalmar", "Hogne",
    "Holger", "Hubert", "Hugo", "Hussain", "Hussein", "Ian", "Ibrahim", "Idar",
    "Idris", "Igor", "Ihor", "Illia", "Ilyas", "Imad", "Imran", "Imre",
    "Ingar", "Inge", "Ingebrigt", "Ingmar", "Ingolf", "Ingvald", "Ingvar", "Ingve",
    "Ioan", "Ion", "Ionut", "Ireneusz", "Isa", "Isaac", "Isac", "Isak",
    "Ismail", "Ivan", "Ivar", "Iver", "Ivo", "Jacek", "Jack", "Jacob",
    "Jahn", "Jakob", "Jakub", "Jamal", "James", "Jamie", "Jan", "Jan-Erik",
    "Janis", "Jann", "Janusz", "Jaran", "Jarand", "Jardar", "Jarl", "Jarle",
    "Jaroslaw", "Jason", "Jean", "Jens", "Jeppe", "Jerzy", "Jesper", "Jim",
    "Jimmy", "Jo", "Joachim", "Joacim", "Joakim", "Joao", "Joar", "Joel",
    "Johan", "Johann", "Johannes", "John", "Johnny", "Jomar", "Jon", "Jonah",
    "Jonas", "Jonatan", "Jonathan", "Jone", "Jonn", "Jonny", "Jøran", "Jørg",
    "Jorge", "Jørgen", "Jørn", "Jørund", "Jose", "Josef", "Joseph", "Joshua",
    "Jostein", "Jozef", "Juan", "Julian", "Julius", "Justin", "Kaare", "Kacper",
    "Kai", "Kaj", "Kamal", "Kamil", "Kåre", "Karim", "Karl", "Karol",
    "Karolis", "Karstein", "Karsten", "Kasper", "Kaspian", "Kato", "Kay", "Kazimierz",
    "Ken", "Kenan", "Kennet", "Kenneth", "Kenny", "Kent", "Kestutis", "Ketil",
    "Kevin", "Khaled", "Khalid", "Khalil", "Kian", "Kim", "Kim-Andre", "Kjartan",
    "Kjell", "Kjetil", "Klaus", "Knut", "Kolbjørn", "Konrad", "Konstantin", "Konstantinos",
    "Kornelius", "Kostiantyn", "Kristen", "Krister", "Kristian", "Kristoffer", "Krystian", "Krzysztof",
    "Kurt", "Kyrre", "Kyrylo", "Lars", "Lars-Erik", "Lasse", "Laurits", "Lauritz",
    "Lavrans", "Leander", "Leif", "Leiv", "Lennart", "Leo", "Leon", "Leonard",
    "Leonardo", "Leonel", "Leszek", "Levi", "Liam", "Liban", "Linas", "Linus",
    "Lionel", "Loke", "Lorentz", "Louie", "Louis", "Luca", "Lucas", "Ludvig",
    "Ludvik", "Luis", "Luka", "Lukas", "Lukasz", "Luke", "Lyder", "Maciej",
    "Mads", "Magnar", "Magne", "Magnus", "Mahad", "Mahamed", "Mahdi", "Maher",
    "Mahmoud", "Maksim", "Maksym", "Maksymilian", "Malik", "Malvin", "Mantas", "Manuel",
    "Marc", "Marcel", "Marcin", "Marco", "Marcus", "Marek", "Marian", "Mario",
    "Marius", "Mariusz", "Mark", "Marko", "Markus", "Marlon", "Martin", "Martinius",
    "Martinus", "Martynas", "Marvin", "Matas", "Mateo", "Mateusz", "Matheo", "Matheus",
    "Mathias", "Mathis", "Matias", "Mats", "Matteo", "Matteus", "Matthew", "Matthias",
    "Mattias", "Mattis", "Matvii", "Max", "Maxim", "Maximilian", "Maximillian", "Md",
    "Mehdi", "Mehmet", "Melvin", "Michael", "Michal", "Michel", "Miguel", "Mihai",
    "Mika", "Mikael", "Mikail", "Mikal", "Mike", "Mikhail", "Mikkel", "Mikolaj",
    "Milan", "Milian", "Milo", "Milos", "Mindaugas", "Minh", "Mio", "Miran",
    "Miroslav", "Miroslaw", "Mohamad", "Mohamed", "Mohammad", "Mohammed", "Mons", "Morgan",
    "Morten", "Mostafa", "Muhammad", "Muhammed", "Murat", "Mustafa", "Mykhailo", "Mykola",
    "Mykyta", "Narve", "Natan", "Nataniel", "Nathan", "Nathaniel", "Natnael", "Nazar",
    "Neil", "Neo", "Nerijus", "Nichlas", "Nicholas", "Nicklas", "Niclas", "Nicolai",
    "Nicolas", "Nicolay", "Niels", "Nikita", "Niklas", "Nikodem", "Nikola", "Nikolai",
    "Nikolas", "Nikolay", "Nils", "Njål", "Noa", "Noah", "Noel", "Norbert",
    "Normann", "Norvald", "Odd", "Oddbjørn", "Oddgeir", "Oddleif", "Oddmund", "Oddvar",
    "Oddvin", "Odin", "Øistein", "Øivind", "Ola", "Olaf", "Olai", "Olav",
    "Ole", "Ole-Christian", "Ole-Jørgen", "Ole-Kristian", "Ole-Martin", "Ole-Petter", "Oleg", "Oleh",
    "Oleksandr", "Oleksii", "Oliver", "Olivier", "Olve", "Omar", "Omer", "Ömer",
    "Omid", "Ørjan", "Ørnulf", "Oscar", "Oskar", "Osman", "Osvald", "Ottar",
    "Otto", "Ove", "Øystein", "Øyvind", "Paal", "Pablo", "Pål", "Patrick",
    "Patrik", "Patryk", "Paul", "Paulius", "Pavel", "Pavlo", "Pawel", "Peder",
    "Pedro", "Pelle", "Per", "Per-Arne", "Per-Erik", "Petar", "Peter", "Petro",
    "Petter", "Philip", "Phillip", "Pierre", "Piotr", "Preben", "Przemyslaw", "Radoslaw",
    "Rafael", "Rafal", "Ragnar", "Ragnvald", "Rainer", "Ralf", "Rami", "Ramunas",
    "Raphael", "Rasmus", "Ravn", "Rayan", "Raymond", "Reidar", "Remi", "Remy",
    "Rene", "Reza", "Ricardo", "Richard", "Rikard", "Rino", "Roald", "Roar",
    "Robel", "Robert", "Robertas", "Roberto", "Robin", "Rodrigo", "Roger", "Roland",
    "Rolandas", "Rolf", "Rolv", "Roman", "Romeo", "Ronald", "Ronnie", "Ronny",
    "Roy", "Ruben", "Rudi", "Rudolf", "Runar", "Rune", "Ruslan", "Ryan",
    "Ryszard", "Saad", "Said", "Salah", "Saleh", "Salman", "Sam", "Sami",
    "Samir", "Samson", "Samuel", "Sander", "Saulius", "Sayed", "Scott", "Sean",
    "Sebastian", "Selmer", "Sergio", "Serhii", "Severin", "Seyed", "Sigbjørn", "Sigfred",
    "Sigmund", "Sigurd", "Sigvald", "Sigvart", "Sigve", "Silas", "Simen", "Simon",
    "Sindre", "Sivert", "Sjur", "Skjalg", "Slawomir", "Snorre", "Solan", "Solomon",
    "Sølve", "Sondre", "Søren", "Ståle", "Stanislav", "Stanislaw", "Stefan", "Steffan",
    "Steffen", "Stein", "Steinar", "Sten", "Stephan", "Stephen", "Steve", "Steven",
    "Stian", "Stig", "Storm", "Sture", "Sturla", "Svein", "Svein-Erik", "Sveinung",
    "Sven", "Svend", "Svenn", "Sverre", "Syed", "Sylwester", "Syver", "Szymon",
    "Tadas", "Tadeusz", "Tage", "Taha", "Tahir", "Tallak", "Tarald", "Tarjei",
    "Ted", "Tellef", "Teo", "Teodor", "Terje", "Thanh", "Theo", "Theodor",
    "Thomas", "Thor", "Thoralf", "Thorbjørn", "Thore", "Thorleif", "Thormod", "Thorstein",
    "Thorvald", "Tim", "Timian", "Timo", "Timothy", "Tobias", "Tom", "Tom-Erik",
    "Tomas", "Tomasz", "Tommy", "Toni", "Tønnes", "Tonny", "Tony", "Tor",
    "Tor-Arne", "Tor-Erik", "Toralf", "Torben", "Torbjørn", "Tord", "Tore", "Torfinn",
    "Torgeir", "Torger", "Torgrim", "Torje", "Torjus", "Torkel", "Torkil", "Torkild",
    "Torleif", "Torleiv", "Tormod", "Torodd", "Torstein", "Torvald", "Tristan", "Tron",
    "Trond", "Troy", "Truls", "Trygve", "Trym", "Tymofii", "Tymur", "Ulf",
    "Ulrik", "Umar", "Usman", "Vadym", "Vaidas", "Valentin", "Valerii", "Van",
    "Varg", "Vasile", "Vasyl", "Vebjørn", "Vegar", "Vegard", "Vemund", "Vetle",
    "Viacheslav", "Victor", "Vidar", "Viggo", "Viktor", "Vilhelm", "Viljar", "Villy",
    "Vincent", "Vitalii", "Vladimir", "Vladyslav", "Volodymyr", "Vytautas", "Waldemar", "Walid",
    "Walter", "Werner", "Widar", "Wieslaw", "Wiggo", "Wiktor", "Wilhelm", "William",
    "Willy", "Wilmer", "Wojciech", "X", "Yahya", "Yaroslav", "Yasin", "Yasir",
    "Yehor", "Yevhen", "Yevhenii", "Yngvar", "Yngve", "Yohannes", "Yonas", "Yosef",
    "Younes", "Yousef", "Youssef", "Yurii", "Yusuf", "Zain", "Zakaria", "Zbigniew",
    "Zdzislaw", "Zoran",
})

# ── Norwegian surnames ───────────────────────────────────────────────────────

NORWEGIAN_SURNAMES: frozenset = frozenset({
    "Aa", "Aabel", "Aaberg", "Aabø", "Aaby", "Aadland", "Aae", "Aaen",
    "Aagaard", "Aagesen", "Aakervik", "Aakre", "Aakvik", "Aaland", "Aalberg", "Aalvik",
    "Aam", "Aamodt", "Aamot", "Aandahl", "Aandal", "Aanensen", "Aanerud", "Aanes",
    "Aanestad", "Aanonsen", "Aanstad", "Aardal", "Aarflot", "Aarhus", "Aarland", "Aarnes",
    "Aarø", "Aarrestad", "Aarsand", "Aarseth", "Aarskog", "Aarsland", "Aarstad", "Aarum",
    "Aarvik", "Aas", "Aasberg", "Aasbø", "Aase", "Aasebø", "Aasen", "Aaserud",
    "Aaseth", "Aasgaard", "Aasheim", "Aasland", "Aaslund", "Aass", "Abbas", "Abdalla",
    "Abdallah", "Abdi", "Abdirahman", "Abdo", "Abdulla", "Abdullah", "Abdullahi", "Abdulle",
    "Abelsen", "Abraha", "Abraham", "Abrahamsen", "Abukar", "Adam", "Adan", "Aden",
    "Adolfsen", "Afzal", "Aga", "Aglen", "Ahmad", "Ahmadi", "Ahmadzai", "Ahmed",
    "Akbari", "Aker", "Akhtar", "Akram", "Aksdal", "Akselsen", "Aksnes", "Alahmad",
    "Alali", "Alam", "Albertsen", "Albrigtsen", "Aleksandersen", "Alexandersen", "Alfheim", "Alfredsen",
    "Alfsen", "Algrøy", "Alhasan", "Alhussein", "Ali", "Alibrahim", "Allum", "Alm",
    "Almaas", "Almås", "Alme", "Almli", "Alnæs", "Alnes", "Alsaker", "Alsos",
    "Alstad", "Alsvik", "Alvær", "Alver", "Alvestad", "Alvheim", "Amble", "Amdahl",
    "Amdal", "Amdam", "Amin", "Amini", "Amiri", "Amlie", "Amundsen", "Anda",
    "Andersen", "Anderson", "Anderssen", "Andersson", "Andorsen", "Andreassen", "Andresen", "Andvik",
    "Anfinsen", "Angell", "Angelsen", "Angeltveit", "Angvik", "Anker", "Anthonsen", "Anti",
    "Antonsen", "Anwar", "Apeland", "Araya", "Arctander", "Arif", "Arneberg", "Arnesen",
    "Arnestad", "Arnevik", "Arnøy", "Arntsen", "Arntzen", "Aronsen", "Arshad", "Arslan",
    "Arvesen", "Asbjørnsen", "Asghar", "Asheim", "Ashraf", "Ask", "Aske", "Askeland",
    "Askevold", "Askildsen", "Askim", "Askvik", "Aslaksen", "Aslam", "Asp", "Aspaas",
    "Aspelund", "Aspen", "Aspenes", "Asphaug", "Astrup", "Aubert", "Auestad", "Augestad",
    "Aukland", "Aulie", "Aunan", "Aune", "Aurdal", "Aure", "Aurstad", "Ausland",
    "Austad", "Austbø", "Austnes", "Austrheim", "Awad", "Axelsen", "Aziz", "Azizi",
    "Baardsen", "Bach", "Backe", "Bækken", "Bærheim", "Bævre", "Bakk", "Bakka",
    "Bakkan", "Bakke", "Bakkehaug", "Bakkejord", "Bakkeli", "Bakkelund", "Bakken", "Bakker",
    "Bakkerud", "Bakketun", "Bakstad", "Ballestad", "Balstad", "Baltzersen", "Bang", "Baran",
    "Bardal", "Bårdsen", "Barka", "Barmen", "Barstad", "Barth", "Bartnes", "Bashir",
    "Bastiansen", "Båtnes", "Bauer", "Bauge", "Baumann", "Baustad", "Bay", "Bech",
    "Beck", "Becker", "Begum", "Bekkelund", "Bekken", "Bekkevold", "Bell", "Belsvik",
    "Bendiksen", "Bendixen", "Bengtsson", "Benjaminsen", "Benonisen", "Bentsen", "Bentzen", "Berdal",
    "Berentsen", "Berg", "Berg-Hansen", "Bergan", "Berge", "Bergem", "Bergene", "Berger",
    "Bergersen", "Bergerud", "Bergesen", "Berget", "Berggren", "Bergh", "Bergheim", "Bergland",
    "Bergli", "Berglund", "Bergman", "Bergmann", "Bergo", "Bergquist", "Bergseng", "Bergset",
    "Bergseth", "Bergstrøm", "Bergsvik", "Bergtun", "Bergum", "Berhane", "Berhe", "Berisha",
    "Berland", "Bernhardsen", "Berntsen", "Berntzen", "Berre", "Berstad", "Bertelsen", "Berthelsen",
    "Bertheussen", "Betten", "Beyene", "Beyer", "Bhatti", "Bibi", "Bilal", "Bilstad",
    "Birkedal", "Birkeland", "Birkeli", "Birkelund", "Birkenes", "Bjelland", "Bjerga", "Bjerk",
    "Bjerkan", "Bjerkås", "Bjerke", "Bjerkeli", "Bjerkelund", "Bjerkestrand", "Bjerkli", "Bjerknes",
    "Bjerkvik", "Bjønnes", "Bjønness", "Bjordal", "Bjørdal", "Bjørgan", "Bjørge", "Bjørgen",
    "Bjørgo", "Bjørgum", "Bjørheim", "Bjørk", "Bjørkås", "Bjørke", "Bjørkedal", "Bjørkhaug",
    "Bjørkheim", "Bjørkli", "Bjørklund", "Bjørkmo", "Bjørknes", "Bjørkum", "Bjorland", "Bjørlo",
    "Bjørn", "Bjørnå", "Bjørndal", "Bjørndalen", "Bjørnerud", "Bjørnes", "Bjørnestad", "Bjørnevik",
    "Bjørnli", "Bjørnø", "Bjørnøy", "Bjørnsen", "Bjørnstad", "Bjorøy", "Bjørseth", "Bjørsvik",
    "Bjørvik", "Bjune", "Blakstad", "Blindheim", "Blix", "Blom", "Blomberg", "Blomquist",
    "Blomvik", "Blystad", "Bø", "Bodin", "Bødtker", "Bøe", "Bøen", "Boge",
    "Bogen", "Bogstrand", "Bøhler", "Bøhmer", "Bøhn", "Bolme", "Bolstad", "Bondarenko",
    "Bondevik", "Bones", "Bonsaksen", "Borch", "Borchgrevink", "Bore", "Borg", "Borgan",
    "Borge", "Borgen", "Borgersen", "Borgund", "Borlaug", "Børnes", "Børresen", "Børseth",
    "Borsheim", "Børsheim", "Børstad", "Børve", "Bostad", "Bøthun", "Botnen", "Botten",
    "Boye", "Bøyum", "Braastad", "Braaten", "Braathen", "Brække", "Brækken", "Brænd",
    "Brænden", "Bragstad", "Brakstad", "Brandal", "Brandt", "Brandtzæg", "Brandvik", "Braseth",
    "Brastad", "Brataas", "Bratberg", "Bråten", "Bråthen", "Bratland", "Bratli", "Bratlie",
    "Bratsberg", "Brattås", "Bratteng", "Brattli", "Bratvold", "Braut", "Bredal", "Bredesen",
    "Breen", "Breiland", "Breistein", "Breivik", "Brekka", "Brekke", "Brekken", "Bremnes",
    "Bremseth", "Brenden", "Brenna", "Brenne", "Brevig", "Brevik", "Bringedal", "Brobakken",
    "Broch", "Brodahl", "Brodersen", "Broen", "Brøndbo", "Brønstad", "Brovold", "Brown",
    "Brox", "Bru", "Bruaset", "Brubakken", "Brudevoll", "Brudvik", "Bruheim", "Bruland",
    "Brun", "Brunborg", "Brunes", "Brunstad", "Brunvoll", "Brustad", "Bruun", "Bruvik",
    "Bruvoll", "Bryhn", "Bryn", "Bryne", "Brynildsen", "Brynjulfsen", "Bu", "Buan",
    "Bue", "Buene", "Buer", "Bugge", "Bugten", "Bui", "Buljo", "Bull",
    "Bunes", "Buraas", "Burud", "Busch", "Busk", "Butt", "Buvarp", "Buvik",
    "By", "Byberg", "Bye", "Byrkjeland", "Bystrøm", "Cao", "Cappelen", "Carlsen",
    "Carlson", "Carlsson", "Caspersen", "Celik", "Celius", "Chan", "Chaudhry", "Chen",
    "Christensen", "Christiansen", "Christoffersen", "Christophersen", "Clausen", "Claussen", "Corneliussen", "Da Silva",
    "Daae", "Dagestad", "Dagsland", "Dahir", "Dahl", "Dahlberg", "Dahle", "Dahlen",
    "Dahlgren", "Dahlstrøm", "Dalaker", "Dalby", "Dale", "Dalen", "Dalene", "Daleng",
    "Dalhaug", "Dalheim", "Dalland", "Dalsbø", "Dalseth", "Dammen", "Dang", "Daniel",
    "Danielsen", "Dar", "David", "Davidsen", "Dehli", "Demir", "Derås", "Devik",
    "Devold", "Didriksen", "Diesen", "Digernes", "Digre", "Dimmen", "Dinh", "Dirdal",
    "Ditlefsen", "Djønne", "Djupvik", "Djuve", "Do", "Doan", "Dokken", "Dørum",
    "Drabløs", "Drage", "Drageset", "Dragland", "Dramstad", "Drange", "Drevland", "Dreyer",
    "Drivenes", "Drønen", "Due", "Duong", "Dvergsdal", "Dyb", "Dybdahl", "Dybdal",
    "Dybvik", "Dybwad", "Dyngeland", "Dyrdal", "Dyrhaug", "Dyrkorn", "Dyrnes", "Dyrøy",
    "Dyrseth", "Dyrstad", "Dyvik", "Ebbesen", "Eckhoff", "Edland", "Edvardsen", "Edvartsen",
    "Eeg", "Eek", "Ege", "Egeberg", "Egeland", "Egeli", "Egenes", "Eggan",
    "Egge", "Eggen", "Eggum", "Eid", "Eide", "Eidem", "Eidet", "Eidissen",
    "Eidsheim", "Eidsvåg", "Eidsvik", "Eie", "Eik", "Eikaas", "Eikås", "Eike",
    "Eikeland", "Eikemo", "Eiken", "Eikenes", "Eikrem", "Eilertsen", "Einan", "Einarsen",
    "Einvik", "Eira", "Ek", "Ekberg", "Ekeberg", "Ekeland", "Ekeli", "Ekelund",
    "Ekerhovd", "Ekker", "Eklund", "Eknes", "Ekre", "Ekrem", "Ekren", "Ekroll",
    "Ekstrøm", "Elde", "Elden", "Eldevik", "Eliassen", "Ellefsen", "Ellingsen", "Elmi",
    "Elnes", "Elstad", "Elton", "Eltvik", "Elvebakk", "Elvenes", "Elverum", "Elvestad",
    "Elvik", "Emanuelsen", "Emberland", "Emblem", "Emilsen", "Endal", "Endresen", "Enersen",
    "Enes", "Eng", "Engan", "Engdal", "Enge", "Engebakken", "Engebretsen", "Engedal",
    "Engeland", "Engelsen", "Engelstad", "Engen", "Engenes", "Enger", "Engeset", "Engeseth",
    "Engevik", "Engh", "Englund", "Engseth", "Engstad", "Engstrøm", "Engum", "Engvik",
    "Enoksen", "Ensrud", "Erdal", "Erga", "Erichsen", "Eriksen", "Eriksrud", "Eriksson",
    "Erikstad", "Erland", "Erlandsen", "Ernstsen", "Ersland", "Erstad", "Ertsås", "Ervik",
    "Eskedal", "Eskeland", "Espe", "Espedal", "Espeland", "Espelid", "Espenes", "Espeseth",
    "Estensen", "Evanger", "Evenrud", "Evensen", "Evenstad", "Evertsen", "Evje", "Evjen",
    "Evju", "Fadnes", "Fagerås", "Fagerbakke", "Fagereng", "Fagerhaug", "Fagerheim", "Fagerholt",
    "Fagerland", "Fagerli", "Fagermo", "Fagernes", "Fagertun", "Fagervik", "Fagervold", "Falch",
    "Falck", "Falk", "Falkenberg", "Fallet", "Fanebust", "Farah", "Fardal", "Farestveit",
    "Farooq", "Farstad", "Fauskanger", "Fauske", "Fedje", "Fenne", "Feragen", "Ferkingstad",
    "Fernandez", "Ferstad", "Fevang", "Fidje", "Fidjeland", "Figenschau", "Figenschou", "Fiksdal",
    "Fimland", "Fimreite", "Finne", "Finnerud", "Finnesand", "Finnøy", "Finseth", "Finsrud",
    "Finstad", "Fischer", "Fiskå", "Fiske", "Fiskerstrand", "Fiskum", "Fiskvik", "Fjær",
    "Fjæreide", "Fjærli", "Fjeld", "Fjeldberg", "Fjelde", "Fjeldheim", "Fjeldstad", "Fjell",
    "Fjellanger", "Fjelldal", "Fjellestad", "Fjellheim", "Fjellstad", "Fjellvang", "Fjermestad", "Fjørtoft",
    "Flaa", "Flaaten", "Flage", "Flataker", "Flatås", "Flatebø", "Flaten", "Flåten",
    "Flatland", "Flatmo", "Flatøy", "Fleischer", "Flem", "Flesland", "Flo", "Flø",
    "Flønes", "Fløtre", "Fløysvik", "Foldnes", "Folgerø", "Folkedal", "Folkestad", "Folkvord",
    "Folland", "Follestad", "Følstad", "Fonn", "Fonnes", "Forberg", "Forbord", "Førde",
    "Føreland", "Forland", "Førland", "Formo", "Fornes", "Førre", "Forsberg", "Forseth",
    "Forsmo", "Førsund", "Fosen", "Foss", "Fossan", "Fossdal", "Fosse", "Fossen",
    "Fosser", "Fosshaug", "Fossheim", "Fossland", "Fossli", "Fossmark", "Fossmo", "Fossnes",
    "Fossum", "Fotland", "Frafjord", "Framnes", "Frank", "Frantzen", "Fredheim", "Fredriksen",
    "Fremstad", "Fretheim", "Friberg", "Friestad", "Frigstad", "Friis", "Frivold", "Frogner",
    "Frøiland", "Frøland", "Frøseth", "Frøshaug", "Frost", "Frostad", "Frøyen", "Frøyland",
    "Frøysa", "Frøystad", "Frydenberg", "Frydenlund", "Fuglem", "Fuglerud", "Fuglestad", "Fure",
    "Furnes", "Furre", "Furset", "Furseth", "Furu", "Furuhaug", "Furuheim", "Furulund",
    "Furunes", "Furuseth", "Fyhn", "Fykse", "Fylkesnes", "Fylling", "Fyllingen",
})

NORWEGIAN_NAMES: frozenset = NORWEGIAN_FEMALE_NAMES | NORWEGIAN_MALE_NAMES | NORWEGIAN_SURNAMES


# ── Common Norwegian words that are NOT person names ─────────────────────────
# Used to suppress NER false positives. Organised by part of speech / domain.

NORWEGIAN_COMMON_WORDS: frozenset = frozenset({
    # ── Determiners / pronouns / articles ────────────────────────────────────
    "den", "det", "de", "ei", "en", "et", "ett",
    "han", "hun", "vi", "dere", "dem", "seg",
    "denne", "dette", "disse", "noen", "noe", "alle", "begge",
    "hvert", "hver", "ingen", "enhver", "man", "meg", "deg", "oss",

    # ── Common prepositions / conjunctions / adverbs ──────────────────────────
    "av", "fra", "til", "for", "med", "uten", "ved", "på", "i", "om",
    "etter", "over", "under", "mellom", "mot", "gjennom", "langs",
    "innen", "inntil", "ifølge", "henhold", "vedrørende",
    "og", "eller", "men", "samt", "både", "enten",
    "fordi", "siden", "når", "hvis", "dersom", "selv",
    "ikke", "også", "bare", "kun", "alt", "allerede",
    "her", "der", "nå", "da", "så", "som", "at", "jo", "vel",
    "ellers", "imidlertid", "likevel", "dessuten", "derfor", "deretter",
    "herved", "hermed", "derimot", "eksplisitt", "henholdsvis",

    # ── Common verbs (as sentence starters or nominalised) ───────────────────
    "er", "var", "blir", "ble", "har", "hadde", "kan", "kunne",
    "vil", "ville", "skal", "skulle", "må", "måtte", "bør", "burde",
    "ser", "ser", "gir", "tar", "gjør", "sier", "kommer", "går",
    "har", "får", "vet", "tror", "mener", "ønsker",
    "utbedres", "justeres", "tilsier", "forutsetter", "innebærer",
    "medfølger", "foreligger", "gjelder", "fremgår", "viser",

    # ── Common nouns – general ────────────────────────────────────────────────
    "hus", "bil", "vei", "gate", "sted", "tid", "dag", "uke", "år",
    "måned", "time", "mann", "dame", "person", "folk", "barn",
    "familie", "arbeid", "jobb", "penger", "mat", "vann", "luft",
    "bok", "brev", "sak", "del", "form", "side", "type", "art",
    "nivå", "grad", "verdi", "antall", "andel", "område", "felt",
    "punkt", "linje", "felt", "gruppe", "lag", "plan", "system",
    "løsning", "mulighet", "behov", "krav", "rett", "plikt",
    "ansvar", "risiko", "kostnad", "pris", "avgift", "skatt",
    "kontrakt", "avtale", "søknad", "klage", "rapport",

    # ── Common nouns – neighbourhood / surroundings ───────────────────────────
    "skole", "barnehage", "butikk", "busstopp", "buss", "tog", "trikk",
    "sentrum", "nærhet", "nabo", "gård", "gate", "park", "plass",
    "kirke", "sykehus", "legesenter", "apotek", "bibliotek", "kino",
    "restaurant", "kafé", "idrettshall", "svømmehall",

    # ── Common adjectives ─────────────────────────────────────────────────────
    "ny", "nytt", "nye", "gammel", "gammelt", "gamle",
    "stor", "stort", "store", "liten", "lite", "små",
    "god", "godt", "gode", "dårlig", "dårlige",
    "lang", "kort", "høy", "lav", "bred", "smal", "dyp",
    "åpen", "lukket", "privat", "offentlig", "felles",
    "norsk", "norske", "utenlandsk", "lokal", "regional", "nasjonal",
    "viktig", "nødvendig", "riktig", "feil", "enkel", "vanskelig",
    "naturlig", "praktisk", "teknisk", "juridisk", "økonomisk",
    "første", "andre", "tredje", "fjerde", "siste", "neste",
    "hele", "halv", "tom", "full", "egen", "annen", "samme",
    "isolert", "integrert", "asfaltert", "automatisk", "innkludert",
    "vedlagte", "følgende", "gjeldende", "overnevnte", "nevnte",
    "skrånende", "terrassert", "opparbeidet",

    # ── Common numerals / quantities ─────────────────────────────────────────
    "én", "ett", "to", "tre", "fire", "fem", "seks", "syv", "åtte", "ni", "ti",
    "første", "andre", "tredje",

    # ── Greetings / discourse markers ────────────────────────────────────────
    "velkommen", "hei", "takk", "vennligst", "obs", "merk", "nb",
    "ps", "dvs", "osv", "jf", "ref", "se", "les",

    # ── Organisational / document terms ──────────────────────────────────────
    "forutsetning", "forutsetninger", "opplysning", "opplysninger",
    "vedlegg", "dokument", "skjema", "signatur", "dato",
    "paragraf", "kapittel", "avsnitt", "punkt", "pkt",
    "tilstandsrapport", "tilstandsanalyse", "tilstandsgrader",
    "tilstandsgradene", "byggemåte", "byggeår",

    # ── Real estate / property terms (supplement to engine.py denylist) ──────
    "eierleilighet", "selveierleilighet", "andelsbolig",
    "fellesareal", "fellesarealer", "fellesgjeld", "felleskostnader",
    "tomteforhold", "terrengforhold", "fuktsikring",
    "etasjeskille", "etasjeskiller", "takkonstruksjon", "veggkonstruksjon",
    "bygningsdeler", "innkjørsel", "garasjeport", "boddør",
    "betonggulv", "portåpner", "referansenivå", "tilstandsvurdert",
    # Inflected / compound forms not caught by the suffix regex
    "inn", "innvendige", "sluk", "kassett", "overgang",
    "boplikt", "boplikten", "planen", "boder",
    "prisantydning", "prisantydningen",
    "attraktiv", "attraktivt", "attraktive",
    "anvendelse", "anvendelsen",
    "oppdragsnr", "oppdragsnummer",
    "vinskap", "vinkapet",
    "bruksendring", "bruksendringer",
    "boligkjøperforsikring", "markedsavtale",
    "reguleringsplankart", "kommuneplankart",
    "eiendomsforvaltning", "forbrukerrådet",
    "kommunalinformasjon", "forbrukerinformasjon",
    "teodolitt", "lengde", "drenering", "dreneringen",
    "adkomstveranda", "adkomsten",
    "lekestativ", "lekeplassen", "planter",
    # Building elements / materials
    "membran", "membranen", "membraner",
    "forholdet", "forholdene",
    # Verbs incorrectly tagged
    "levere", "leverer", "levert",
    # Cadastral / property reference abbreviations
    "gnr", "bnr", "snr",
    # Norwegian direction/position adjectives
    "øvre", "nedre", "vestre", "østre", "nordre", "søndre",

    # ── Days of week / months (NER sometimes tags these) ─────────────────────
    "mandag", "tirsdag", "onsdag", "torsdag", "fredag", "lørdag", "søndag",
    "januar", "februar", "mars", "april", "mai", "juni",
    "juli", "august", "september", "oktober", "november", "desember",
})
