"""
Norwegian name lists and common-word denylist for PII filtering.

Sources: SSB (Statistics Norway) most-common first/last names (200+ persons),
plus common Norwegian vocabulary used to suppress NER false positives.
"""

# ── Norwegian first names (female) ───────────────────────────────────────────

NORWEGIAN_FEMALE_NAMES: frozenset = frozenset({
    "Aagot", "Aase", "Aashild", "Aasta", "Abigail", "Ada", "Adele", "Adelen",
    "Adelina", "Adriana", "Agata", "Agathe", "Agne", "Agnes", "Agnete", "Agnethe",
    "Agnieszka", "Ågot", "Aida", "Aila", "Aileen", "Ailin", "Aimee", "Aina",
    "Aisha", "Alaa", "Alba", "Aleksandra", "Alette", "Alexandra", "Alfhild", "Alia",
    "Alice", "Alicia", "Alicja", "Alida", "Alina", "Aline", "Alisa", "Alise",
    "Alla", "Alma", "Alona", "Alva", "Alvhild", "Alvilde", "Amal", "Amalia",
    "Amalie", "Amanda", "Amelia", "Amelie", "Amina", "Amira", "Amna", "Amy",
    "Ana", "Anastasia", "Anastasiia", "Anbjørg", "Andrea", "Andreea", "Andrine", "Ane",
    "Aneta", "Anett", "Anette", "Angela", "Angelica", "Angelika", "Angelina", "Anhelina",
    "Anine", "Anisa", "Anita", "Anja", "Anlaug", "Ann", "Ann-Christin", "Ann-Helen",
    "Ann-Karin", "Ann-Kristin", "Ann-Mari", "Anna", "Annabelle", "Annbjørg", "Anne", "Anne-Berit",
    "Anne-Brit", "Anne-Britt", "Anne-Grete", "Anne-Grethe", "Anne-Kari", "Anne-Karin", "Anne-Kristin", "Anne-Lene",
    "Anne-Lise", "Anne-Mari", "Anne-Marie", "Anne-Marit", "Anne-Mette", "Anne-Sofie", "Anneli", "Annelin",
    "Annelise", "Annette", "Anni", "Annie", "Annika", "Anniken", "Annlaug", "Anny",
    "Antonia", "Antonina", "Aria", "Ariana", "Ariel", "Arina", "Arna", "Arnhild",
    "Arya", "Åsa", "Asbjørg", "Åse", "Asha", "Åshild", "Aslaug", "Åslaug",
    "Asma", "Åsne", "Asta", "Åsta", "Astri", "Astrid", "Athena", "Aud",
    "Audhild", "Audny", "Aurelia", "Aurora", "Ausra", "Ava", "Aya", "Ayan",
    "Ayesha", "Ayla", "Aylin", "Ayse", "Azra", "Barbara", "Barbro", "Beata",
    "Beate", "Beathe", "Beatrice", "Belinda", "Bella", "Benedicte", "Benedikte", "Bente",
    "Benthe", "Bergit", "Bergliot", "Bergljot", "Berit", "Berta", "Bertha", "Bertine",
    "Betina", "Bettina", "Betty", "Bianca", "Bibi", "Birgit", "Birgith", "Birgitta",
    "Birgitte", "Birte", "Birthe", "Bjørg", "Bodil", "Borghild", "Borgny", "Bozena",
    "Brit", "Brita", "Brith", "Britt", "Britta", "Brynhild", "Bushra", "Camilla",
    "Carina", "Carine", "Carla", "Carmen", "Carolina", "Caroline", "Cassandra", "Catharina",
    "Catherine", "Cathrin", "Cathrine", "Catrine", "Cecilia", "Cecilie", "Celia", "Celin",
    "Celina", "Celine", "Cesilie", "Charlotte", "Chloe", "Christel", "Christiane", "Christin",
    "Christina", "Christine", "Cicilie", "Cindy", "Clara", "Claudia", "Connie", "Cornelia",
    "Cristina", "Dagfrid", "Dagmar", "Dagny", "Dagrun", "Daiva", "Dalia", "Dana",
    "Daniela", "Daniella", "Danielle", "Danuta", "Daria", "Daryna", "Deborah", "Denise",
    "Desiree", "Diana", "Dina", "Dominika", "Dordi", "Doris", "Dorota", "Dorthe",
    "Dorthea", "Ea", "Ebba", "Edda", "Edel", "Eden", "Edit", "Edita",
    "Edith", "Edle", "Edna", "Edny", "Edyta", "Egle", "Eila", "Eileen",
    "Eilen", "Eilin", "Eir", "Eira", "Eiril", "Eirill", "Eirin", "Eivor",
    "Ekaterina", "Ela", "Elbjørg", "Eldbjørg", "Eldrid", "Elea", "Eleah", "Elen",
    "Elena", "Eleni", "Elfrid", "Eli", "Eliana", "Elida", "Elif", "Elin",
    "Elina", "Eline", "Elinor", "Elisa", "Elisabet", "Elisabeth", "Elise", "Eliza",
    "Elizabeth", "Ella", "Elle", "Ellen", "Elli", "Ellie", "Ellinor", "Elly",
    "Elma", "Elna", "Elsa", "Else", "Else-Marie", "Elsie", "Elvira", "Elzbieta",
    "Ema", "Embla", "Emelie", "Emely", "Emilia", "Emilie", "Emilija", "Emily",
    "Emina", "Emine", "Emma", "Emmeli", "Emmeline", "Emmy", "Enya", "Erica",
    "Erika", "Erle", "Erna", "Ester", "Esther", "Eva", "Evelina", "Eveline",
    "Evelyn", "Evy", "Ewa", "Ewelina", "Fadumo", "Faiza", "Fanny", "Farah",
    "Fatemeh", "Fatima", "Fatma", "Fay", "Felicia", "Fie", "Filippa", "Fiona",
    "Fredrikke", "Freja", "Freya", "Frid", "Frida", "Fride", "Frøya", "Frøydis",
    "Gabija", "Gabriela", "Gabriele", "Gabriella", "Gabrielle", "Galina", "Gerd", "Gerda",
    "Gina", "Gine", "Gintare", "Gitte", "Gjertrud", "Gloria", "Gøril", "Grace",
    "Grazyna", "Greta", "Grete", "Gretha", "Grethe", "Gro", "Gry", "Gudny",
    "Gudrun", "Gudveig", "Gun", "Gunda", "Gunhild", "Gunlaug", "Gunn", "Gunnbjørg",
    "Gunnhild", "Gunnlaug", "Gunnvor", "Gunvor", "Guri", "Guro", "Gyda", "Hafsa",
    "Hailey", "Hala", "Haldis", "Halima", "Halldis", "Halyna", "Hamdi", "Hana",
    "Hanan", "Hanna", "Hannah", "Hanne", "Harriet", "Hatice", "Hedda", "Hedvig",
    "Hege", "Heidi", "Helen", "Helena", "Helene", "Helga", "Helin", "Helle",
    "Hennie", "Henny", "Henriette", "Henrikke", "Herborg", "Herdis", "Hermine", "Hiba",
    "Hild", "Hilda", "Hilde", "Hildegunn", "Hildur", "Hilma", "Hjørdis", "Hodan",
    "Hong", "Huda", "Hulda", "Iben", "Ida", "Idun", "Idunn", "Ieva",
    "Ilona", "Iman", "Ina", "Ine", "Ines", "Inga", "Inge", "Ingebjørg",
    "Ingeborg", "Ingelin", "Inger", "Inger-Johanne", "Inger-Lise", "Inger-Marie", "Ingerid", "Ingfrid",
    "Inghild", "Ingjerd", "Ingri", "Ingrid", "Ingrida", "Ingun", "Ingunn", "Ingvil",
    "Ingvild", "Ingvill", "Inna", "Iqra", "Iren", "Irena", "Irene", "Irina",
    "Iris", "Irma", "Irmelin", "Iryna", "Isa", "Isabel", "Isabell", "Isabella",
    "Isabelle", "Iselin", "Isra", "Iva", "Ivana", "Iwona", "Izabela", "Jacqueline",
    "Jamila", "Jana", "Jane", "Janet", "Janicke", "Janina", "Janita", "Janne",
    "Janniche", "Jannicke", "Jannike", "Jasmin", "Jasmina", "Jasmine", "Jeanett", "Jeanette",
    "Jelena", "Jenni", "Jennie", "Jennifer", "Jenny", "Jessica", "Jette", "Jill",
    "Joan", "Joanna", "Jofrid", "Johanna", "Johanne", "Jolanta", "Jorid", "Jorun",
    "Jorunn", "Josefine", "Josephine", "Judit", "Judith", "Julia", "Juliana", "Juliane",
    "Julianne", "Julie", "Julija", "June", "Juni", "Jurgita", "Justyna", "Kaia",
    "Kaisa", "Kaja", "Kajsa", "Kamila", "Kamile", "Kamilla", "Karen", "Kari",
    "Kari-Anne", "Karianne", "Karin", "Karina", "Karine", "Karla", "Karolina", "Karoline",
    "Karyna", "Katarina", "Katarzyna", "Kate", "Katerina", "Kateryna", "Katharina", "Kathe",
    "Katherine", "Kathinka", "Kathrin", "Kathrine", "Katinka", "Katja", "Katrin", "Katrina",
    "Katrine", "Kaya", "Kelly", "Kerstin", "Khadija", "Kim", "Kine", "Kinga",
    "Kira", "Kirsten", "Kirsti", "Kitty", "Kjellaug", "Kjellfrid", "Kjellrun", "Kjersti",
    "Kjerstin", "Klara", "Klaudia", "Konstanse", "Kornelia", "Kristel", "Kristi", "Kristiane",
    "Kristin", "Kristina", "Kristine", "Krystyna", "Kseniia", "Laila", "Lajla", "Lana",
    "Lara", "Larisa", "Larysa", "Laura", "Layla", "Lea", "Leah", "Leikny",
    "Leila", "Lejla", "Lena", "Lene", "Leni", "Leona", "Leonora", "Lerke",
    "Leyla", "Lia", "Liana", "Lidia", "Lidiia", "Lilian", "Liliana", "Liliia",
    "Lilja", "Lilje", "Lill", "Lilli", "Lillian", "Lilly", "Lily", "Lin",
    "Lina", "Linda", "Lindis", "Line", "Linea", "Linn", "Linnea", "Lisa",
    "Lisbet", "Lisbeth", "Lise", "Liss", "Liubov", "Liudmila", "Liudmyla", "Liv",
    "Liva", "Live", "Livia", "Liz", "Liza", "Lone", "Lorena", "Lotta",
    "Lotte", "Louisa", "Louise", "Lovise", "Lucia", "Lucie", "Lucy", "Luna",
    "Lydia", "Lykke", "Ma", "Madeleine", "Madelen", "Madelene", "Madina", "Magda",
    "Magdalena", "Magna", "Magnhild", "Magni", "Magny", "Maha", "Mai", "Mai-Britt",
    "Maia", "Maida", "Maiken", "Maj", "Maja", "Malak", "Malena", "Malene",
    "Målfrid", "Malgorzata", "Mali", "Malika", "Malin", "Manuela", "Maren", "Margaret",
    "Margareth", "Margarita", "Margit", "Margot", "Margrete", "Margrethe", "Margun", "Margunn",
    "Marharyta", "Mari", "Mari-Ann", "Maria", "Mariam", "Marian", "Mariana", "Mariann",
    "Marianna", "Marianne", "Marie", "Mariel", "Mariell", "Marielle", "Mariia", "Marija",
    "Marika", "Marina", "Marion", "Marit", "Marita", "Marlen", "Marlena", "Marlene",
    "Marry", "Marta", "Marte", "Martha", "Marthe", "Marthine", "Martina", "Martine",
    "Martyna", "Marwa", "Mary", "Mary-Ann", "Maryam", "Maryan", "Maryna", "Marzena",
    "Mathea", "Mathilda", "Mathilde", "Matilda", "Matilde", "Maud", "May", "May-Britt",
    "May-Liss", "Maya", "Maylen", "Medina", "Melanie", "Melina", "Melinda", "Melisa",
    "Melissa", "Merete", "Merethe", "Meryem", "Mette", "Mia", "Michaela", "Michelle",
    "Mie", "Mihaela", "Mikaela", "Mila", "Milana", "Mildrid", "Milena", "Milica",
    "Milla", "Mille", "Millie", "Mimmi", "Mina", "Mira", "Miranda", "Miriam",
    "Mirjam", "Molly", "Mona", "Monica", "Monika", "Møyfrid", "Muna", "My",
    "Nada", "Nadia", "Nadiia", "Nadine", "Nadja", "Naima", "Najma", "Nancy",
    "Nanna", "Naomi", "Nasrin", "Natalia", "Natalie", "Nataliia", "Nataliya", "Natasha",
    "Nathalie", "Nelia", "Nellie", "Nelly", "Ngoc", "Nicole", "Nicoline", "Nikola",
    "Nikoline", "Nina", "Ninni", "Noelle", "Noor", "Nora", "Norah", "Norma",
    "Norunn", "Nour", "Nova", "Oda", "Oddbjørg", "Oddfrid", "Oddlaug", "Oddny",
    "Oddrun", "Oddveig", "Oksana", "Olaug", "Olava", "Olea", "Oleksandra", "Olena",
    "Olga", "Olha", "Oline", "Olivia", "Oliwia", "Othelie", "Othilie", "Otilie",
    "Pamela", "Patricia", "Patrycja", "Paula", "Paulina", "Pauline", "Peggy", "Pernille",
    "Petra", "Phuong", "Pia", "Polina", "Rabia", "Rachel", "Ragna", "Ragne",
    "Ragnhild", "Ragni", "Rahel", "Rahma", "Raisa", "Rakel", "Ramona", "Rana",
    "Randi", "Rania", "Rannveig", "Ranveig", "Rasa", "Rebecca", "Rebecka", "Rebekka",
    "Regina", "Regine", "Reidun", "Reidunn", "Renata", "Renate", "Renathe", "Renee",
    "Rigmor", "Rikke", "Rina", "Rita", "Ronja", "Rønnaug", "Rosa", "Rose",
    "Roza", "Ruby", "Runa", "Rut", "Ruta", "Ruth", "Saba", "Sabina",
    "Sabine", "Sabrina", "Sadia", "Safa", "Safia", "Saga", "Sahar", "Sahra",
    "Saima", "Sally", "Salma", "Samantha", "Samira", "Sana", "Sandra", "Sanja",
    "Sanna", "Sanne", "Sara", "Sarah", "Savannah", "Selam", "Selina", "Seline",
    "Selma", "Senait", "Serina", "Serine", "Sham", "Sharon", "Sheila", "Shirin",
    "Sidra", "Sidsel", "Sienna", "Sigfrid", "Signe", "Signy", "Sigrid", "Sigrun",
    "Sigrunn", "Siham", "Silja", "Silje", "Silvia", "Simona", "Simone", "Sina",
    "Sine", "Siren", "Siri", "Siril", "Sissel", "Siv", "Siw", "Snefrid",
    "Sofia", "Sofie", "Sofiia", "Sofija", "Sol", "Solbjørg", "Solfrid", "Solgunn",
    "Solrun", "Solvår", "Solveig", "Sølvi", "Solvor", "Sonia", "Sonja", "Sophia",
    "Sophie", "Stella", "Stephanie", "Stina", "Stine", "Sumaya", "Sunniva", "Susan",
    "Susann", "Susanna", "Susanne", "Suzanne", "Svanhild", "Svetlana", "Svitlana", "Syeda",
    "Sylvi", "Sylvia", "Sylwia", "Synne", "Synnøve", "Synøve", "Tale", "Tamara",
    "Tania", "Tanja", "Tanya", "Tara", "Tatiana", "Tatjana", "Tea", "Teresa",
    "Terese", "Tetiana", "Thale", "Thanh", "Thea", "Thelma", "Theresa", "Therese",
    "Thi", "Thilde", "Thora", "Thordis", "Thu", "Thuy", "Tia", "Tilda",
    "Tilde", "Tilla", "Tina", "Tine", "Tiril", "Tirill", "Tomine", "Tone",
    "Tonje", "Tora", "Torbjørg", "Tordis", "Torgunn", "Torhild", "Tori", "Toril",
    "Torild", "Torill", "Torun", "Torunn", "Tove", "Trine", "Trine-Lise", "Trude",
    "Turi", "Turid", "Tuva", "Tyra", "Ulla", "Ulrikke", "Una", "Une",
    "Unn", "Unni", "Urszula", "Vaida", "Valborg", "Valentina", "Valentyna", "Valeria",
    "Valeriia", "Vanessa", "Vanja", "Vår", "Vårin", "Vega", "Venche", "Venke",
    "Vera", "Veronica", "Veronika", "Veslemøy", "Vibecke", "Vibeke", "Victoria", "Vida",
    "Vigdis", "Viktoria", "Viktoriia", "Viktorija", "Vilde", "Vilja", "Vilje", "Vilma",
    "Viola", "Violeta", "Vira", "Vita", "Vivi", "Vivian", "Wanja", "Wenche",
    "Wencke", "Wendy", "Wenke", "Weronika", "Wigdis", "Wiktoria", "Wilma", "Wioletta",
    "X", "Yana", "Yara", "Yasmin", "Yelyzaveta", "Yeva", "Yevheniia", "Ylva",
    "Yngvild", "Yordanos", "Yuliia", "Yusra", "Yvonne", "Zahra", "Zainab", "Zara",
    "Zeinab", "Zeynep", "Zlata", "Zoe", "Zofia", "Zuzanna",
})

# ── Norwegian first names (male) ─────────────────────────────────────────────

NORWEGIAN_MALE_NAMES: frozenset = frozenset({
    "Aage", "Aaron", "Aasmund", "Abbas", "Abdallah", "Abdi", "Abdirahman", "Abdul",
    "Abdulkadir", "Abdullah", "Abdullahi", "Abdulrahman", "Abel", "Abraham", "Adam", "Adel",
    "Adem", "Adil", "Adnan", "Ådne", "Adrian", "Åge", "Agnar", "Ahmad",
    "Ahmed", "Ahmet", "Aiden", "Ailo", "Akram", "Aksel", "Alaa", "Alan",
    "Albert", "Albin", "Alejandro", "Aleksandar", "Aleksander", "Aleksandr", "Aleksandrs", "Alex",
    "Alexander", "Alexandru", "Alf", "Alfred", "Ali", "Allan", "Alv", "Alvar",
    "Alvin", "Amanuel", "Amar", "Amer", "Amin", "Amir", "Ammar", "Amund",
    "Anas", "Anatolii", "Anders", "Andre", "Andreas", "Andrei", "Andrej", "Andres",
    "Andrew", "Andrii", "Andris", "Andrius", "Andrzej", "Angel", "Annar", "Ansgar",
    "Anthony", "Anton", "Antoni", "Antonio", "Anwar", "Aram", "Are", "Ari",
    "Arian", "Arild", "Arkadiusz", "Arman", "Armin", "Arn", "Arne", "Arnfinn",
    "Arnljot", "Arnold", "Arnstein", "Arnt", "Arnulf", "Aron", "Artem", "Arthur",
    "Artur", "Arturas", "Arunas", "Arve", "Arvid", "Arvin", "Arvydas", "Aryan",
    "Asad", "Asbjørn", "Asgeir", "Ask", "Aslak", "Asle", "Asmund", "Åsmund",
    "Atlas", "Atle", "Audrius", "Audun", "August", "Aurimas", "Axel", "Ayman",
    "Ayub", "Aziz", "Baard", "Balder", "Bård", "Bartlomiej", "Bartosz", "Bastian",
    "Ben", "Bendik", "Bengt", "Benjamin", "Benny", "Bent", "Bernard", "Bernhard",
    "Bernt", "Bertil", "Bilal", "Birger", "Birk", "Bjarne", "Bjarte", "Bjørge",
    "Bjørn", "Bjørn-Erik", "Bjørnar", "Bo", "Bogdan", "Boguslaw", "Bohdan", "Borgar",
    "Børge", "Boris", "Børre", "Brage", "Brede", "Brian", "Bror", "Bruno",
    "Brynjar", "Brynjulf", "Carl", "Carlos", "Carsten", "Casper", "Caspian", "Cato",
    "Cezary", "Charles", "Charlie", "Chris", "Christen", "Christer", "Christian", "Christoffer",
    "Christopher", "Claes", "Claus", "Colin", "Conrad", "Constantin", "Cornelius", "Cristian",
    "Dag", "Dagfinn", "Dainius", "Damian", "Damir", "Dan", "Dani", "Danial",
    "Daniel", "Daniil", "Danny", "Danylo", "Darius", "Dariusz", "David", "Davyd",
    "Dawid", "Dawit", "Deividas", "Dejan", "Denis", "Dennis", "Denys", "Didrik",
    "Diego", "Dmytro", "Dominic", "Dominik", "Donatas", "Dovydas", "Dragan", "Dylan",
    "Ebbe", "Eddie", "Edgar", "Edgaras", "Edin", "Edmund", "Eduard", "Eduardo",
    "Edvard", "Edvin", "Edvinas", "Edward", "Edwin", "Egidijus", "Egil", "Eigil",
    "Eik", "Eilert", "Eilev", "Eilif", "Einar", "Eirik", "Eivind", "Eldar",
    "Eliah", "Elian", "Elias", "Elling", "Elliot", "Elvin", "Emanuel", "Emil",
    "Emilian", "Emilio", "Emir", "Emmanuel", "Emre", "Emrik", "Endre", "Enes",
    "Eric", "Erik", "Erland", "Erlend", "Erling", "Ernst", "Esben", "Eskil",
    "Eskild", "Espen", "Esten", "Ethan", "Evald", "Evaldas", "Evan", "Even",
    "Eystein", "Eyvind", "Fabian", "Faisal", "Falk", "Farhad", "Felix", "Ferdinand",
    "Fernando", "Filip", "Fillip", "Finn", "Flemming", "Florian", "Florin", "Francis",
    "Francisco", "Franciszek", "Frank", "Frans", "Fred", "Freddy", "Frederik", "Fredrick",
    "Fredrik", "Fridtjof", "Frikk", "Frithjof", "Frits", "Fritz", "Frode", "Gabriel",
    "Gard", "Gaute", "Gediminas", "Geir", "Georg", "George", "Georgios", "Gerhard",
    "Gert", "Gheorghe", "Giedrius", "Gintaras", "Gisle", "Gjermund", "Gjert", "Glen",
    "Glenn", "Goran", "Gøran", "Gorm", "Grzegorz", "Gudbrand", "Gudmund", "Gunnar",
    "Gunvald", "Gustav", "Guttorm", "Haakon", "Haavard", "Hadi", "Håkon", "Haldor",
    "Halfdan", "Hallgeir", "Hallstein", "Hallvard", "Halvard", "Halvor", "Hamid", "Hamza",
    "Hans", "Hans-Petter", "Harald", "Haris", "Harry", "Hasan", "Hassan", "Hauk",
    "Håvar", "Håvard", "Heine", "Helge", "Helmer", "Henning", "Henri", "Henrik",
    "Henry", "Henryk", "Herman", "Hermann", "Hermod", "Hilmar", "Hjalmar", "Hogne",
    "Holger", "Hubert", "Hugo", "Hussain", "Hussein", "Ian", "Ibrahim", "Idar",
    "Idris", "Igor", "Ihor", "Illia", "Ilyas", "Imad", "Imran", "Imre",
    "Ingar", "Inge", "Ingebrigt", "Ingmar", "Ingolf", "Ingvald", "Ingvar", "Ingve",
    "Ioan", "Ion", "Ionut", "Ireneusz", "Isa", "Isaac", "Isac", "Isak",
    "Ismail", "Ivan", "Ivar", "Iver", "Ivo", "Jacek", "Jack", "Jacob",
    "Jahn", "Jakob", "Jakub", "Jamal", "James", "Jamie", "Jan", "Jan-Erik",
    "Janis", "Jann", "Janusz", "Jaran", "Jarand", "Jardar", "Jarl", "Jarle",
    "Jaroslaw", "Jason", "Jean", "Jens", "Jeppe", "Jerzy", "Jesper", "Jim",
    "Jimmy", "Jo", "Joachim", "Joacim", "Joakim", "Joao", "Joar", "Joel",
    "Johan", "Johann", "Johannes", "John", "Johnny", "Jomar", "Jon", "Jonah",
    "Jonas", "Jonatan", "Jonathan", "Jone", "Jonn", "Jonny", "Jøran", "Jørg",
    "Jorge", "Jørgen", "Jørn", "Jørund", "Jose", "Josef", "Joseph", "Joshua",
    "Jostein", "Jozef", "Juan", "Julian", "Julius", "Justin", "Kaare", "Kacper",
    "Kai", "Kaj", "Kamal", "Kamil", "Kåre", "Karim", "Karl", "Karol",
    "Karolis", "Karstein", "Karsten", "Kasper", "Kaspian", "Kato", "Kay", "Kazimierz",
    "Ken", "Kenan", "Kennet", "Kenneth", "Kenny", "Kent", "Kestutis", "Ketil",
    "Kevin", "Khaled", "Khalid", "Khalil", "Kian", "Kim", "Kim-Andre", "Kjartan",
    "Kjell", "Kjetil", "Klaus", "Knut", "Kolbjørn", "Konrad", "Konstantin", "Konstantinos",
    "Kornelius", "Kostiantyn", "Kristen", "Krister", "Kristian", "Kristoffer", "Krystian", "Krzysztof",
    "Kurt", "Kyrre", "Kyrylo", "Lars", "Lars-Erik", "Lasse", "Laurits", "Lauritz",
    "Lavrans", "Leander", "Leif", "Leiv", "Lennart", "Leo", "Leon", "Leonard",
    "Leonardo", "Leonel", "Leszek", "Levi", "Liam", "Liban", "Linas", "Linus",
    "Lionel", "Loke", "Lorentz", "Louie", "Louis", "Luca", "Lucas", "Ludvig",
    "Ludvik", "Luis", "Luka", "Lukas", "Lukasz", "Luke", "Lyder", "Maciej",
    "Mads", "Magnar", "Magne", "Magnus", "Mahad", "Mahamed", "Mahdi", "Maher",
    "Mahmoud", "Maksim", "Maksym", "Maksymilian", "Malik", "Malvin", "Mantas", "Manuel",
    "Marc", "Marcel", "Marcin", "Marco", "Marcus", "Marek", "Marian", "Mario",
    "Marius", "Mariusz", "Mark", "Marko", "Markus", "Marlon", "Martin", "Martinius",
    "Martinus", "Martynas", "Marvin", "Matas", "Mateo", "Mateusz", "Matheo", "Matheus",
    "Mathias", "Mathis", "Matias", "Mats", "Matteo", "Matteus", "Matthew", "Matthias",
    "Mattias", "Mattis", "Matvii", "Max", "Maxim", "Maximilian", "Maximillian", "Md",
    "Mehdi", "Mehmet", "Melvin", "Michael", "Michal", "Michel", "Miguel", "Mihai",
    "Mika", "Mikael", "Mikail", "Mikal", "Mike", "Mikhail", "Mikkel", "Mikolaj",
    "Milan", "Milian", "Milo", "Milos", "Mindaugas", "Minh", "Mio", "Miran",
    "Miroslav", "Miroslaw", "Mohamad", "Mohamed", "Mohammad", "Mohammed", "Mons", "Morgan",
    "Morten", "Mostafa", "Muhammad", "Muhammed", "Murat", "Mustafa", "Mykhailo", "Mykola",
    "Mykyta", "Narve", "Natan", "Nataniel", "Nathan", "Nathaniel", "Natnael", "Nazar",
    "Neil", "Neo", "Nerijus", "Nichlas", "Nicholas", "Nicklas", "Niclas", "Nicolai",
    "Nicolas", "Nicolay", "Niels", "Nikita", "Niklas", "Nikodem", "Nikola", "Nikolai",
    "Nikolas", "Nikolay", "Nils", "Njål", "Noa", "Noah", "Noel", "Norbert",
    "Normann", "Norvald", "Odd", "Oddbjørn", "Oddgeir", "Oddleif", "Oddmund", "Oddvar",
    "Oddvin", "Odin", "Øistein", "Øivind", "Ola", "Olaf", "Olai", "Olav",
    "Ole", "Ole-Christian", "Ole-Jørgen", "Ole-Kristian", "Ole-Martin", "Ole-Petter", "Oleg", "Oleh",
    "Oleksandr", "Oleksii", "Oliver", "Olivier", "Olve", "Omar", "Omer", "Ömer",
    "Omid", "Ørjan", "Ørnulf", "Oscar", "Oskar", "Osman", "Osvald", "Ottar",
    "Otto", "Ove", "Øystein", "Øyvind", "Paal", "Pablo", "Pål", "Patrick",
    "Patrik", "Patryk", "Paul", "Paulius", "Pavel", "Pavlo", "Pawel", "Peder",
    "Pedro", "Pelle", "Per", "Per-Arne", "Per-Erik", "Petar", "Peter", "Petro",
    "Petter", "Philip", "Phillip", "Pierre", "Piotr", "Preben", "Przemyslaw", "Radoslaw",
    "Rafael", "Rafal", "Ragnar", "Ragnvald", "Rainer", "Ralf", "Rami", "Ramunas",
    "Raphael", "Rasmus", "Ravn", "Rayan", "Raymond", "Reidar", "Remi", "Remy",
    "Rene", "Reza", "Ricardo", "Richard", "Rikard", "Rino", "Roald", "Roar",
    "Robel", "Robert", "Robertas", "Roberto", "Robin", "Rodrigo", "Roger", "Roland",
    "Rolandas", "Rolf", "Rolv", "Roman", "Romeo", "Ronald", "Ronnie", "Ronny",
    "Roy", "Ruben", "Rudi", "Rudolf", "Runar", "Rune", "Ruslan", "Ryan",
    "Ryszard", "Saad", "Said", "Salah", "Saleh", "Salman", "Sam", "Sami",
    "Samir", "Samson", "Samuel", "Sander", "Saulius", "Sayed", "Scott", "Sean",
    "Sebastian", "Selmer", "Sergio", "Serhii", "Severin", "Seyed", "Sigbjørn", "Sigfred",
    "Sigmund", "Sigurd", "Sigvald", "Sigvart", "Sigve", "Silas", "Simen", "Simon",
    "Sindre", "Sivert", "Sjur", "Skjalg", "Slawomir", "Snorre", "Solan", "Solomon",
    "Sølve", "Sondre", "Søren", "Ståle", "Stanislav", "Stanislaw", "Stefan", "Steffan",
    "Steffen", "Stein", "Steinar", "Sten", "Stephan", "Stephen", "Steve", "Steven",
    "Stian", "Stig", "Storm", "Sture", "Sturla", "Svein", "Svein-Erik", "Sveinung",
    "Sven", "Svend", "Svenn", "Sverre", "Syed", "Sylwester", "Syver", "Szymon",
    "Tadas", "Tadeusz", "Tage", "Taha", "Tahir", "Tallak", "Tarald", "Tarjei",
    "Ted", "Tellef", "Teo", "Teodor", "Terje", "Thanh", "Theo", "Theodor",
    "Thomas", "Thor", "Thoralf", "Thorbjørn", "Thore", "Thorleif", "Thormod", "Thorstein",
    "Thorvald", "Tim", "Timian", "Timo", "Timothy", "Tobias", "Tom", "Tom-Erik",
    "Tomas", "Tomasz", "Tommy", "Toni", "Tønnes", "Tonny", "Tony", "Tor",
    "Tor-Arne", "Tor-Erik", "Toralf", "Torben", "Torbjørn", "Tord", "Tore", "Torfinn",
    "Torgeir", "Torger", "Torgrim", "Torje", "Torjus", "Torkel", "Torkil", "Torkild",
    "Torleif", "Torleiv", "Tormod", "Torodd", "Torstein", "Torvald", "Tristan", "Tron",
    "Trond", "Troy", "Truls", "Trygve", "Trym", "Tymofii", "Tymur", "Ulf",
    "Ulrik", "Umar", "Usman", "Vadym", "Vaidas", "Valentin", "Valerii", "Van",
    "Varg", "Vasile", "Vasyl", "Vebjørn", "Vegar", "Vegard", "Vemund", "Vetle",
    "Viacheslav", "Victor", "Vidar", "Viggo", "Viktor", "Vilhelm", "Viljar", "Villy",
    "Vincent", "Vitalii", "Vladimir", "Vladyslav", "Volodymyr", "Vytautas", "Waldemar", "Walid",
    "Walter", "Werner", "Widar", "Wieslaw", "Wiggo", "Wiktor", "Wilhelm", "William",
    "Willy", "Wilmer", "Wojciech", "X", "Yahya", "Yaroslav", "Yasin", "Yasir",
    "Yehor", "Yevhen", "Yevhenii", "Yngvar", "Yngve", "Yohannes", "Yonas", "Yosef",
    "Younes", "Yousef", "Youssef", "Yurii", "Yusuf", "Zain", "Zakaria", "Zbigniew",
    "Zdzislaw", "Zoran",
})

# ── Norwegian surnames ───────────────────────────────────────────────────────

NORWEGIAN_SURNAMES: frozenset = frozenset({
    "Aa", "Aabel", "Aaberg", "Aabø", "Aaby", "Aadland", "Aae", "Aaen",
    "Aagaard", "Aagesen", "Aakervik", "Aakre", "Aakvik", "Aaland", "Aalberg", "Aalvik",
    "Aam", "Aamodt", "Aamot", "Aandahl", "Aandal", "Aanensen", "Aanerud", "Aanes",
    "Aanestad", "Aanonsen", "Aanstad", "Aardal", "Aarflot", "Aarhus", "Aarland", "Aarnes",
    "Aarø", "Aarrestad", "Aarsand", "Aarseth", "Aarskog", "Aarsland", "Aarstad", "Aarum",
    "Aarvik", "Aas", "Aasberg", "Aasbø", "Aase", "Aasebø", "Aasen", "Aaserud",
    "Aaseth", "Aasgaard", "Aasheim", "Aasland", "Aaslund", "Aass", "Abbas", "Abdalla",
    "Abdallah", "Abdi", "Abdirahman", "Abdo", "Abdulla", "Abdullah", "Abdullahi", "Abdulle",
    "Abelsen", "Abraha", "Abraham", "Abrahamsen", "Abukar", "Adam", "Adan", "Aden",
    "Ådland", "Adolfsen", "Afzal", "Aga", "Aglen", "Ahmad", "Ahmadi", "Ahmadzai",
    "Ahmed", "Akbari", "Aker", "Akhtar", "Akram", "Åkre", "Aksdal", "Akselsen",
    "Aksnes", "Alahmad", "Alali", "Alam", "Albertsen", "Albrigtsen", "Aleksandersen", "Alexandersen",
    "Alfheim", "Alfredsen", "Alfsen", "Algrøy", "Alhasan", "Alhussein", "Ali", "Alibrahim",
    "Allum", "Alm", "Almaas", "Almås", "Alme", "Almli", "Alnæs", "Alnes",
    "Alsaker", "Alsos", "Alstad", "Alsvik", "Alvær", "Alver", "Alvestad", "Alvheim",
    "Amble", "Amdahl", "Amdal", "Amdam", "Amin", "Amini", "Amiri", "Amlie",
    "Åmodt", "Amundsen", "Anda", "Andersen", "Anderson", "Anderssen", "Andersson", "Andorsen",
    "Andreassen", "Andresen", "Andvik", "Ånensen", "Ånestad", "Anfinsen", "Angell", "Angelsen",
    "Angeltveit", "Angvik", "Anker", "Anthonsen", "Anti", "Antonsen", "Anwar", "Apeland",
    "Araya", "Arctander", "Årdal", "Arif", "Arneberg", "Årnes", "Arnesen", "Arnestad",
    "Arnevik", "Arnøy", "Arntsen", "Arntzen", "Aronsen", "Årseth", "Arshad", "Arslan",
    "Arvesen", "Årvik", "Ås", "Asbjørnsen", "Åsebø", "Åsen", "Asghar", "Asheim",
    "Åsheim", "Ashraf", "Ask", "Aske", "Askeland", "Askevold", "Askildsen", "Askim",
    "Askvik", "Aslaksen", "Aslam", "Åsland", "Asp", "Aspaas", "Aspelund", "Aspen",
    "Aspenes", "Asphaug", "Astrup", "Aubert", "Auestad", "Augestad", "Aukland", "Aulie",
    "Aunan", "Aune", "Aurdal", "Aure", "Aurstad", "Ausland", "Austad", "Austbø",
    "Austnes", "Austrheim", "Awad", "Axelsen", "Aziz", "Azizi", "Baardsen", "Bach",
    "Backe", "Bækken", "Bærheim", "Bævre", "Bakk", "Bakka", "Bakkan", "Bakke",
    "Bakkehaug", "Bakkejord", "Bakkeli", "Bakkelund", "Bakken", "Bakker", "Bakkerud", "Bakketun",
    "Bakstad", "Ballestad", "Balstad", "Baltzersen", "Bang", "Baran", "Bardal", "Bårdsen",
    "Barka", "Barmen", "Barstad", "Barth", "Bartnes", "Bashir", "Bastiansen", "Båtnes",
    "Bauer", "Bauge", "Baumann", "Baustad", "Bay", "Bech", "Beck", "Becker",
    "Begum", "Bekkelund", "Bekken", "Bekkevold", "Bell", "Belsvik", "Bendiksen", "Bendixen",
    "Bengtsson", "Benjaminsen", "Benonisen", "Bentsen", "Bentzen", "Berdal", "Berentsen", "Berg",
    "Berg-Hansen", "Bergan", "Berge", "Bergem", "Bergene", "Berger", "Bergersen", "Bergerud",
    "Bergesen", "Berget", "Berggren", "Bergh", "Bergheim", "Bergland", "Bergli", "Berglund",
    "Bergman", "Bergmann", "Bergo", "Bergquist", "Bergseng", "Bergset", "Bergseth", "Bergstrøm",
    "Bergsvik", "Bergtun", "Bergum", "Berhane", "Berhe", "Berisha", "Berland", "Bernhardsen",
    "Berntsen", "Berntzen", "Berre", "Berstad", "Bertelsen", "Berthelsen", "Bertheussen", "Betten",
    "Beyene", "Beyer", "Bhatti", "Bibi", "Bilal", "Bilstad", "Birkedal", "Birkeland",
    "Birkeli", "Birkelund", "Birkenes", "Bjelland", "Bjerga", "Bjerk", "Bjerkan", "Bjerkås",
    "Bjerke", "Bjerkeli", "Bjerkelund", "Bjerkestrand", "Bjerkli", "Bjerknes", "Bjerkvik", "Bjønnes",
    "Bjønness", "Bjordal", "Bjørdal", "Bjørgan", "Bjørge", "Bjørgen", "Bjørgo", "Bjørgum",
    "Bjørheim", "Bjørk", "Bjørkås", "Bjørke", "Bjørkedal", "Bjørkhaug", "Bjørkheim", "Bjørkli",
    "Bjørklund", "Bjørkmo", "Bjørknes", "Bjørkum", "Bjorland", "Bjørlo", "Bjørn", "Bjørnå",
    "Bjørndal", "Bjørndalen", "Bjørnerud", "Bjørnes", "Bjørnestad", "Bjørnevik", "Bjørnli", "Bjørnø",
    "Bjørnøy", "Bjørnsen", "Bjørnstad", "Bjorøy", "Bjørseth", "Bjørsvik", "Bjørvik", "Bjune",
    "Blakstad", "Blindheim", "Blix", "Blom", "Blomberg", "Blomquist", "Blomvik", "Blystad",
    "Bø", "Bodin", "Bødtker", "Bøe", "Bøen", "Boge", "Bogen", "Bogstrand",
    "Bøhler", "Bøhmer", "Bøhn", "Bolme", "Bolstad", "Bondarenko", "Bondevik", "Bones",
    "Bonsaksen", "Borch", "Borchgrevink", "Bore", "Borg", "Borgan", "Borge", "Borgen",
    "Borgersen", "Borgund", "Borlaug", "Børnes", "Børresen", "Børseth", "Borsheim", "Børsheim",
    "Børstad", "Børve", "Bostad", "Bøthun", "Botnen", "Botten", "Boye", "Bøyum",
    "Braastad", "Braaten", "Braathen", "Brække", "Brækken", "Brænd", "Brænden", "Bragstad",
    "Brakstad", "Brandal", "Brandt", "Brandtzæg", "Brandvik", "Braseth", "Brastad", "Brataas",
    "Bratberg", "Bråten", "Bråthen", "Bratland", "Bratli", "Bratlie", "Bratsberg", "Brattås",
    "Bratteng", "Brattli", "Bratvold", "Braut", "Bredal", "Bredesen", "Breen", "Breiland",
    "Breistein", "Breivik", "Brekka", "Brekke", "Brekken", "Bremnes", "Bremseth", "Brenden",
    "Brenna", "Brenne", "Brevig", "Brevik", "Bringedal", "Brobakken", "Broch", "Brodahl",
    "Brodersen", "Broen", "Brøndbo", "Brønstad", "Brovold", "Brown", "Brox", "Bru",
    "Bruaset", "Brubakken", "Brudevoll", "Brudvik", "Bruheim", "Bruland", "Brun", "Brunborg",
    "Brunes", "Brunstad", "Brunvoll", "Brustad", "Bruun", "Bruvik", "Bruvoll", "Bryhn",
    "Bryn", "Bryne", "Brynildsen", "Brynjulfsen", "Bu", "Buan", "Bue", "Buene",
    "Buer", "Bugge", "Bugten", "Bui", "Buljo", "Bull", "Bunes", "Buraas",
    "Burud", "Busch", "Busk", "Butt", "Buvarp", "Buvik", "By", "Byberg",
    "Bye", "Byrkjeland", "Bystrøm", "Cao", "Cappelen", "Carlsen", "Carlson", "Carlsson",
    "Caspersen", "Celik", "Celius", "Chan", "Chaudhry", "Chen", "Christensen", "Christiansen",
    "Christoffersen", "Christophersen", "Clausen", "Claussen", "Corneliussen", "Da Silva", "Daae", "Dagestad",
    "Dagsland", "Dahir", "Dahl", "Dahlberg", "Dahle", "Dahlen", "Dahlgren", "Dahlstrøm",
    "Dalaker", "Dalby", "Dale", "Dalen", "Dalene", "Daleng", "Dalhaug", "Dalheim",
    "Dalland", "Dalsbø", "Dalseth", "Dammen", "Dang", "Daniel", "Danielsen", "Dar",
    "David", "Davidsen", "Dehli", "Demir", "Derås", "Devik", "Devold", "Didriksen",
    "Diesen", "Digernes", "Digre", "Dimmen", "Dinh", "Dirdal", "Ditlefsen", "Djønne",
    "Djupvik", "Djuve", "Do", "Doan", "Dokken", "Dørum", "Drabløs", "Drage",
    "Drageset", "Dragland", "Dramstad", "Drange", "Drevland", "Dreyer", "Drivenes", "Drønen",
    "Due", "Duong", "Dvergsdal", "Dyb", "Dybdahl", "Dybdal", "Dybvik", "Dybwad",
    "Dyngeland", "Dyrdal", "Dyrhaug", "Dyrkorn", "Dyrnes", "Dyrøy", "Dyrseth", "Dyrstad",
    "Dyvik", "Ebbesen", "Eckhoff", "Edland", "Edvardsen", "Edvartsen", "Eeg", "Eek",
    "Ege", "Egeberg", "Egeland", "Egeli", "Egenes", "Eggan", "Egge", "Eggen",
    "Eggum", "Eid", "Eide", "Eidem", "Eidet", "Eidissen", "Eidsheim", "Eidsvåg",
    "Eidsvik", "Eie", "Eik", "Eikaas", "Eikås", "Eike", "Eikeland", "Eikemo",
    "Eiken", "Eikenes", "Eikrem", "Eilertsen", "Einan", "Einarsen", "Einvik", "Eira",
    "Ek", "Ekberg", "Ekeberg", "Ekeland", "Ekeli", "Ekelund", "Ekerhovd", "Ekker",
    "Eklund", "Eknes", "Ekre", "Ekrem", "Ekren", "Ekroll", "Ekstrøm", "Elde",
    "Elden", "Eldevik", "Eliassen", "Ellefsen", "Ellingsen", "Elmi", "Elnes", "Elstad",
    "Elton", "Eltvik", "Elvebakk", "Elvenes", "Elverum", "Elvestad", "Elvik", "Emanuelsen",
    "Emberland", "Emblem", "Emilsen", "Endal", "Endresen", "Enersen", "Enes", "Eng",
    "Engan", "Engdal", "Enge", "Engebakken", "Engebretsen", "Engedal", "Engeland", "Engelsen",
    "Engelstad", "Engen", "Engenes", "Enger", "Engeset", "Engeseth", "Engevik", "Engh",
    "Englund", "Engseth", "Engstad", "Engstrøm", "Engum", "Engvik", "Enoksen", "Ensrud",
    "Erdal", "Erga", "Erichsen", "Eriksen", "Eriksrud", "Eriksson", "Erikstad", "Erland",
    "Erlandsen", "Ernstsen", "Ersland", "Erstad", "Ertsås", "Ervik", "Eskedal", "Eskeland",
    "Espe", "Espedal", "Espeland", "Espelid", "Espenes", "Espeseth", "Estensen", "Evanger",
    "Evenrud", "Evensen", "Evenstad", "Evertsen", "Evje", "Evjen", "Evju", "Fadnes",
    "Fagerås", "Fagerbakke", "Fagereng", "Fagerhaug", "Fagerheim", "Fagerholt", "Fagerland", "Fagerli",
    "Fagermo", "Fagernes", "Fagertun", "Fagervik", "Fagervold", "Falch", "Falck", "Falk",
    "Falkenberg", "Fallet", "Fanebust", "Farah", "Fardal", "Farestveit", "Farooq", "Farstad",
    "Fauskanger", "Fauske", "Fedje", "Fenne", "Feragen", "Ferkingstad", "Fernandez", "Ferstad",
    "Fevang", "Fidje", "Fidjeland", "Figenschau", "Figenschou", "Fiksdal", "Fimland", "Fimreite",
    "Finne", "Finnerud", "Finnesand", "Finnøy", "Finseth", "Finsrud", "Finstad", "Fischer",
    "Fiskå", "Fiske", "Fiskerstrand", "Fiskum", "Fiskvik", "Fjær", "Fjæreide", "Fjærli",
    "Fjeld", "Fjeldberg", "Fjelde", "Fjeldheim", "Fjeldstad", "Fjell", "Fjellanger", "Fjelldal",
    "Fjellestad", "Fjellheim", "Fjellstad", "Fjellvang", "Fjermestad", "Fjørtoft", "Flaa", "Flaaten",
    "Flage", "Flataker", "Flatås", "Flatebø", "Flaten", "Flåten", "Flatland", "Flatmo",
    "Flatøy", "Fleischer", "Flem", "Flesland", "Flo", "Flø", "Flønes", "Fløtre",
    "Fløysvik", "Foldnes", "Folgerø", "Folkedal", "Folkestad", "Folkvord", "Folland", "Follestad",
    "Følstad", "Fonn", "Fonnes", "Forberg", "Forbord", "Førde", "Føreland", "Forland",
    "Førland", "Formo", "Fornes", "Førre", "Forsberg", "Forseth", "Forsmo", "Førsund",
    "Fosen", "Foss", "Fossan", "Fossdal", "Fosse", "Fossen", "Fosser", "Fosshaug",
    "Fossheim", "Fossland", "Fossli", "Fossmark", "Fossmo", "Fossnes", "Fossum", "Fotland",
    "Frafjord", "Framnes", "Frank", "Frantzen", "Fredheim", "Fredriksen", "Fremstad", "Fretheim",
    "Friberg", "Friestad", "Frigstad", "Friis", "Frivold", "Frogner", "Frøiland", "Frøland",
    "Frøseth", "Frøshaug", "Frost", "Frostad", "Frøyen", "Frøyland", "Frøysa", "Frøystad",
    "Frydenberg", "Frydenlund", "Fuglem", "Fuglerud", "Fuglestad", "Fure", "Furnes", "Furre",
    "Furset", "Furseth", "Furu", "Furuhaug", "Furuheim", "Furulund", "Furunes", "Furuseth",
    "Fyhn", "Fykse", "Fylkesnes", "Fylling", "Fyllingen", "Gaard", "Gaarder", "Gabrielsen",
    "Gamst", "Gangstad", "Garberg", "Garcia", "Gården", "Garnes", "Garshol", "Garvik",
    "Gashi", "Gåsland", "Gaup", "Gausdal", "Gaustad", "Gebremariam", "Gebremedhin", "Gebremichael",
    "Georgsen", "Gerhardsen", "Giæver", "Gilberg", "Gilde", "Gilje", "Gill", "Gillebo",
    "Gimre", "Gimse", "Giske", "Gjedrem", "Gjelstad", "Gjelsten", "Gjelsvik", "Gjendem",
    "Gjengedal", "Gjengstø", "Gjerde", "Gjerdingen", "Gjerdrum", "Gjerløw", "Gjermundsen", "Gjernes",
    "Gjersøe", "Gjerstad", "Gjersvik", "Gjertsen", "Gjeruldsen", "Gjervik", "Gjesdal", "Gjessing",
    "Gjestad", "Gjestvang", "Gjøen", "Gjønnes", "Gjøsund", "Glad", "Gleditsch", "Glesnes",
    "Gloppen", "Goa", "Godø", "Goksøyr", "Gonzalez", "Graff", "Gram", "Gramstad",
    "Gran", "Granås", "Granberg", "Grande", "Granerud", "Granheim", "Granli", "Granlund",
    "Granly", "Granmo", "Grannes", "Granum", "Grav", "Gravdahl", "Gravdal", "Gravem",
    "Grebstad", "Green", "Gregersen", "Greve", "Grimnes", "Grimsmo", "Grimsrud", "Grimstad",
    "Grinde", "Grinden", "Grindhaug", "Grindheim", "Grini", "Grødem", "Grønås", "Grønbech",
    "Grønberg", "Grøndahl", "Grøndal", "Grøndalen", "Grøneng", "Grongstad", "Grønhaug", "Grønli",
    "Grønlie", "Grønlien", "Grønlund", "Grønn", "Grønnestad", "Grønnevik", "Grønning", "Grønningsæter",
    "Grønsberg", "Grønseth", "Grønstad", "Grønvik", "Grønvold", "Grøstad", "Grøtan", "Grøterud",
    "Groth", "Grotle", "Grøtte", "Grøtting", "Grov", "Groven", "Grude", "Grue",
    "Grytten", "Gudbrandsen", "Guddal", "Gudmestad", "Gudmundsen", "Gulbrandsen", "Guldahl", "Guldberg",
    "Gullaksen", "Gulli", "Gulliksen", "Gundersen", "Gunnarsen", "Gunnarsson", "Gunnerød", "Gunnerud",
    "Gunnes", "Gunnestad", "Gupta", "Gussiås", "Gustad", "Gustafsson", "Gustavsen", "Gustavson",
    "Guttorm", "Guttormsen", "Gyland", "Gylland", "Ha", "Haagensen", "Haakonsen", "Haaland",
    "Haarberg", "Haarr", "Haarstad", "Haave", "Haavik", "Habberstad", "Habbestad", "Habibi",
    "Habte", "Haddal", "Haddeland", "Hadland", "Hægeland", "Hætta", "Hafstad", "Haga",
    "Hagberg", "Hage", "Hageland", "Hagelund", "Hagen", "Hagenes", "Hågensen", "Hagerup",
    "Hagland", "Haglund", "Hagos", "Håheim", "Haidari", "Haider", "Haile", "Haji",
    "Håkonsen", "Håland", "Halden", "Haldorsen", "Hall", "Hallan", "Halland", "Hallberg",
    "Halle", "Halleland", "Hallem", "Halleraker", "Hallingstad", "Hals", "Halse", "Halsen",
    "Halseth", "Halstensen", "Halvorsen", "Halvorsrud", "Hamborg", "Hamid", "Hammer", "Hammeren",
    "Hammerø", "Hammersland", "Hammerstad", "Hammervold", "Hamnes", "Hamre", "Hana", "Handeland",
    "Hånes", "Hannestad", "Hannisdal", "Hansen", "Hanssen", "Hansson", "Hanstad", "Håpnes",
    "Haraldseid", "Haraldsen", "Haraldstad", "Haram", "Harbo", "Hardy", "Hareide", "Harestad",
    "Harila", "Harkestad", "Harlem", "Harnes", "Harstad", "Hårstad", "Harsvik", "Hartmann",
    "Hartveit", "Hartvigsen", "Hartviksen", "Hasan", "Hasani", "Hashemi", "Hashi", "Hasle",
    "Hassan", "Hassani", "Hassel", "Hasselberg", "Hasund", "Hatland", "Hatlem", "Hatlen",
    "Hatlestad", "Hatlevik", "Hatløy", "Hatteland", "Hauan", "Haug", "Haugan", "Hauge",
    "Haugen", "Hauger", "Haugerud", "Haugland", "Haugli", "Hauglid", "Haugnes", "Haugo",
    "Haugom", "Haugsdal", "Haugseth", "Haugstad", "Haugsvær", "Haugum", "Haugvaldstad", "Haukaas",
    "Haukås", "Haukedal", "Haukeland", "Haukenes", "Haukland", "Hausken", "Hauso", "Haveland",
    "Haver", "Havik", "Håvik", "Havn", "Havnen", "Hay", "Hebnes", "Heen",
    "Hegdal", "Hegg", "Heggdal", "Hegge", "Heggedal", "Heggelund", "Heggem", "Heggen",
    "Heggernes", "Heggestad", "Heggheim", "Heggland", "Hegglund", "Heggøy", "Heggset", "Hegland",
    "Hegna", "Hegre", "Hegstad", "Heia", "Heiberg", "Heidari", "Heide", "Heien",
    "Heier", "Heim", "Heimark", "Heimdal", "Heimstad", "Heistad", "Heitmann", "Helberg",
    "Heldal", "Helgeland", "Helgerud", "Helgesen", "Helgestad", "Helgevold", "Helgheim", "Helgøy",
    "Hella", "Hellan", "Helland", "Helle", "Hellebø", "Hellebust", "Helleland", "Hellem",
    "Hellenes", "Helleren", "Hellerud", "Hellesø", "Hellesøy", "Hellevik", "Helliesen", "Hellstrøm",
    "Hellum", "Helmersen", "Helset", "Helseth", "Helstad", "Heltne", "Helvik", "Hem",
    "Hemmingsen", "Hemnes", "Henden", "Henningsen", "Hennum", "Henriksen", "Hepsø", "Herdlevær",
    "Herfindal", "Herheim", "Herigstad", "Herland", "Hermann", "Hermansen", "Hernæs", "Hernandez",
    "Hernes", "Herstad", "Hervik", "Hesjedal", "Heskestad", "Hesselberg", "Hessen", "Hestad",
    "Hestenes", "Hestetun", "Hestnes", "Hestvik", "Hetland", "Heum", "Hevrøy", "Hexeberg",
    "Heyerdahl", "Hidle", "Hilde", "Hildre", "Hildrum", "Hille", "Hilleren", "Hillestad",
    "Hilmarsen", "Hilstad", "Hindenes", "Hinna", "Hirsi", "Hjelde", "Hjelle", "Hjelm",
    "Hjelmeland", "Hjelseth", "Hjelvik", "Hjønnevåg", "Hjørnevik", "Hjort", "Hjorth", "Hjortland",
    "Hjulstad", "Ho", "Hoang", "Hobberstad", "Hoddevik", "Hodne", "Hodneland", "Hodzic",
    "Hoel", "Hoem", "Hoff", "Hoffmann", "Hofseth", "Hofstad", "Hoftun", "Høgås",
    "Høgberg", "Høgli", "Høglund", "Hognestad", "Høgset", "Høgseth", "Hogstad", "Høiberg",
    "Høiby", "Høie", "Høiland", "Høines", "Høiseth", "Høistad", "Høivik", "Hojem",
    "Hokstad", "Hol", "Holand", "Holberg", "Holden", "Hole", "Holen", "Holgersen",
    "Hølland", "Hollund", "Holm", "Holmberg", "Holme", "Holmedal", "Holmefjord", "Holmen",
    "Holmgren", "Holmøy", "Holmsen", "Holmstrøm", "Holmvik", "Holsen", "Holst", "Holstad",
    "Holt", "Holta", "Holtan", "Holte", "Holten", "Holter", "Holtet", "Holth",
    "Holthe", "Holum", "Holvik", "Homme", "Honningsvåg", "Hop", "Hope", "Hopen",
    "Hopland", "Hopsdal", "Hordnes", "Hordvik", "Horgen", "Horn", "Horne", "Hornnes",
    "Horntvedt", "Horpestad", "Horten", "Horvei", "Hoset", "Hoseth", "Hosseini", "Hotvedt",
    "Hov", "Hovd", "Hovda", "Hovdal", "Hovde", "Hovden", "Hove", "Hoven",
    "Høvik", "Hovin", "Hovind", "Hovland", "Høydahl", "Høydal", "Høye", "Høyem",
    "Høyer", "Høyland", "Høyvik", "Huang", "Hult", "Hunnes", "Hunstad", "Hurlen",
    "Husa", "Husabø", "Husby", "Husdal", "Huse", "Husebø", "Huseby", "Husevåg",
    "Husøy", "Hussain", "Hussaini", "Hussein", "Hustad", "Hustoft", "Hustveit", "Husum",
    "Huus", "Huynh", "Hval", "Hvattum", "Hveding", "Hveem", "Hvidsten", "Hylland",
    "Hynne", "Hystad", "Ibrahim", "Iden", "Idland", "Idris", "Idsø", "Idsøe",
    "Igland", "Ihle", "Ihlen", "Ilyas", "Imran", "Ims", "Indahl", "Indergård",
    "Indrebø", "Ingebretsen", "Ingebrigtsen", "Ingvaldsen", "Innvær", "Iqbal", "Irgens", "Isachsen",
    "Isaksen", "Isdahl", "Isdal", "Isene", "Islam", "Ismail", "Issa", "Istad",
    "Ivanov", "Ivanova", "Iversen", "Jacobsen", "Jæger", "Jafari", "Jahnsen", "Jahr",
    "Jahren", "Jakobsen", "Jama", "Jamal", "Jansen", "Jansson", "Jåsund", "Javed",
    "Jensen", "Jensrud", "Jenssen", "Jentoft", "Jeppesen", "Jerstad", "Jespersen", "Jessen",
    "Jevnaker", "Jevne", "Joa", "Joakimsen", "Johannesen", "Johannessen", "Johansen", "Johanson",
    "Johansson", "Johnsen", "Johnson", "Johnsrud", "Johnstad", "Jonas", "Jonassen", "Jones",
    "Jonsson", "Jønsson", "Jordal", "Jordalen", "Jordan", "Jordet", "Jordheim", "Jørgensen",
    "Jørstad", "Josdal", "Josefsen", "Jøssang", "Jovanovic", "Juell", "Juliussen", "Justad",
    "Juul", "Juvik", "Kaasa", "Kahrs", "Kahsay", "Kaland", "Kaldestad", "Kaldheim",
    "Kalland", "Kalleberg", "Kallestad", "Kallevik", "Kalstad", "Kalvik", "Kandal", "Kanestrøm",
    "Kapstad", "Kara", "Karim", "Karimi", "Karlsen", "Karlson", "Karlsrud", "Karlsson",
    "Karlstad", "Karlstrøm", "Karoliussen", "Kårstad", "Karstensen", "Kåsa", "Kasin", "Kaspersen",
    "Kastrati", "Kaupang", "Kaur", "Kausar", "Kavli", "Kaya", "Khalaf", "Khalid",
    "Khalil", "Khan", "Kibsgaard", "Kidane", "Kielland", "Kihle", "Kiil", "Kildahl",
    "Kildal", "Kilde", "Kile", "Kilen", "Killi", "Kim", "Kind", "King",
    "Kinn", "Kirkeby", "Kirkerud", "Kirkevold", "Kirkhus", "Kirknes", "Kittelsen", "Kittilsen",
    "Kjær", "Kjærland", "Kjærnes", "Kjærstad", "Kjærvik", "Kjeilen", "Kjeldsberg", "Kjeldsen",
    "Kjellevold", "Kjelsberg", "Kjelsrud", "Kjelstad", "Kjelstrup", "Kjerstad", "Kjesbu", "Kjøde",
    "Kjølberg", "Kjølstad", "Kjørstad", "Kjørsvik", "Kjos", "Kjøsnes", "Klæboe", "Klakegg",
    "Klausen", "Klaussen", "Klavenes", "Klein", "Kleiv", "Kleiveland", "Kleiven", "Klemetsen",
    "Klepp", "Kleppa", "Kleppe", "Klette", "Klev", "Kleveland", "Kleven", "Klingenberg",
    "Klokk", "Kloster", "Kløvstad", "Klungland", "Klungtveit", "Klyve", "Knapstad", "Knarvik",
    "Knoph", "Knotten", "Knudsen", "Knutsen", "Koch", "Kofoed", "Kolås", "Kolberg",
    "Kolbjørnsen", "Kolle", "Kollstrøm", "Kolltveit", "Kolnes", "Kolseth", "Kolsrud", "Kolstad",
    "Kolstø", "Kommedal", "Kongshaug", "Kongsrud", "Kongsvik", "Konradsen", "Koppang", "Kopperud",
    "Koren", "Korneliussen", "Korslund", "Korsmo", "Korsnes", "Korsvik", "Korsvold", "Kovacevic",
    "Kovalenko", "Kowalczyk", "Kowalski", "Kraft", "Kråkenes", "Krane", "Krasniqi", "Kravchenko",
    "Kringstad", "Kristensen", "Kristiansen", "Kristoffersen", "Krog", "Krogh", "Krogsæter", "Krogsrud",
    "Krogstad", "Krohn", "Kroken", "Krokstad", "Kronstad", "Krosby", "Kruger", "Krüger",
    "Kruse", "Kulseth", "Kumar", "Kvaal", "Kvaale", "Kværner", "Kvale", "Kvåle",
    "Kvalheim", "Kvalnes", "Kvalø", "Kvaløy", "Kvalsund", "Kvalsvik", "Kvalvåg", "Kvalvik",
    "Kvam", "Kvame", "Kvamme", "Kvammen", "Kvamsdal", "Kvandal", "Kvande", "Kvarme",
    "Kvarsnes", "Kvello", "Kvernberg", "Kverneland", "Kvernmo", "Kvia", "Kvien", "Kvilhaug",
    "Kvinge", "Kvinlaug", "Kvinnesland", "Kvistad", "Kydland", "Kyllingstad", "Kyvik", "Laastad",
    "Lade", "Lægreid", "Lærum", "Lagesen", "Laland", "Lam", "Lamo", "Lampe",
    "Landa", "Lande", "Landmark", "Landro", "Landrø", "Landsem", "Landsverk", "Langaas",
    "Langåker", "Langås", "Langbråten", "Lange", "Langedal", "Langeland", "Langen", "Langerud",
    "Langfeldt", "Langhelle", "Langholm", "Langli", "Langlo", "Langmo", "Langnes", "Langø",
    "Langørgen", "Langøy", "Langset", "Langseth", "Langvik", "Larsen", "Larssen", "Larsson",
    "Lassen", "Låstad", "Laugen", "Lauritsen", "Lauritzen", "Laursen", "Lausund", "Lauten",
    "Lauvås", "Lauvrak", "Lavik", "Le", "Lea", "Lee", "Lehmann", "Lehn",
    "Lehne", "Leidland", "Leikanger", "Leiknes", "Leikvoll", "Lein", "Leine", "Leira",
    "Leirdal", "Leirvåg", "Leirvik", "Leistad", "Leite", "Leithe", "Leivestad", "Leknes",
    "Lekven", "Lende", "Lenes", "Leonhardsen", "Leren", "Lerøy", "Lerstad", "Lerum",
    "Lervåg", "Lervik", "Letnes", "Levang", "Li", "Lia", "Liabø", "Lian",
    "Liberg", "Lid", "Lidal", "Lie", "Lied", "Lien", "Lieng", "Lier",
    "Liknes", "Liland", "Lilleås", "Lilleberg", "Lillebø", "Lilleby", "Lilleeng", "Lilleengen",
    "Lillegård", "Lillehagen", "Lillejord", "Lilleland", "Lillemo", "Lilleng", "Lillestøl", "Lilletvedt",
    "Lillevik", "Lima", "Lind", "Lindahl", "Lindal", "Lindanger", "Lindås", "Lindberg",
    "Lindblad", "Linde", "Lindgaard", "Lindgren", "Lindheim", "Lindhjem", "Lindholm", "Lindland",
    "Lindquist", "Lindqvist", "Lindseth", "Lindstad", "Lindstrøm", "Lindvik", "Linge", "Linnerud",
    "Liseth", "Liu", "Lium", "Liverød", "Ljones", "Ljosland", "Løberg", "Løchen",
    "Lockert", "Lode", "Lødemel", "Loe", "Loen", "Lofthus", "Log", "Løge",
    "Lohne", "Løkås", "Løken", "Løkke", "Løkkeberg", "Løkken", "Lokøy", "Løland",
    "Lomeland", "Lona", "Lone", "Longva", "Lønning", "Lopez", "Lorentsen", "Lorentzen",
    "Løset", "Løseth", "Lossius", "Lothe", "Løtveit", "Løvaas", "Løvås", "Løvberg",
    "Løvdal", "Løver", "Løvik", "Løvland", "Løvli", "Løvlie", "Løvlien", "Løvold",
    "Løvoll", "Løvseth", "Løvstad", "Løyning", "Lu", "Ludvigsen", "Ludviksen", "Lund",
    "Lundal", "Lundberg", "Lundby", "Lunde", "Lundeby", "Lundekvam", "Lundemo", "Lunden",
    "Lunder", "Lundestad", "Lundgård", "Lundgren", "Lundh", "Lundquist", "Lura", "Lyche",
    "Lydersen", "Lygre", "Lyng", "Lyngmo", "Lyngstad", "Lyngvær", "Lynum", "Lysaker",
    "Lyse", "Lysen", "Lysgård", "Lyshaug", "Lysne", "Lysø", "Lyssand", "Lystad",
    "Madland", "Madsen", "Mæhle", "Mæhlum", "Mæhre", "Mæland", "Mæle", "Mælen",
    "Magerøy", "Magnus", "Magnussen", "Magnusson", "Mahamed", "Mahammed", "Mahamud", "Mahmood",
    "Mahmoud", "Mahmud", "Majid", "Måkestad", "Malde", "Malik", "Malin", "Malm",
    "Malme", "Malmedal", "Malmin", "Malmo", "Malvik", "Mandal", "Mandelid", "Mannes",
    "Mannsverk", "Marcussen", "Mardal", "Marken", "Markhus", "Markovic", "Markussen", "Marøy",
    "Marstein", "Martens", "Marthinsen", "Marthinussen", "Martin", "Martinez", "Martinsen", "Martinussen",
    "Marvik", "Mathiassen", "Mathiesen", "Mathisen", "Matre", "Maudal", "Maurstad", "Mauseth",
    "Mazur", "Mebrahtu", "Medhus", "Meek", "Mehari", "Mehl", "Mehlum", "Mehmood",
    "Mehus", "Meidell", "Meier", "Meisingset", "Meland", "Melberg", "Melbø", "Melby",
    "Melbye", "Melgård", "Melheim", "Melhus", "Meling", "Mellem", "Mellemstrand", "Mellingen",
    "Mellum", "Melsom", "Melum", "Melvold", "Mentzoni", "Merkesdal", "Meyer", "Michael",
    "Michaelsen", "Michalsen", "Michelsen", "Midtbø", "Midtgård", "Midthun", "Midtskogen", "Midttun",
    "Midttveit", "Midtun", "Mikaelsen", "Mikalsen", "Mikkelborg", "Mikkelsen", "Milde", "Miljeteig",
    "Miller", "Minde", "Minge", "Mir", "Mirza", "Misje", "Misund", "Mittet",
    "Mjåland", "Mjånes", "Mjelde", "Mjøen", "Mjølhus", "Mjønes", "Mjøs", "Mo",
    "Moa", "Moan", "Moberg", "Moe", "Moen", "Mogen", "Mogstad", "Møgster",
    "Mohamad", "Mohamed", "Mohammad", "Mohammadi", "Mohammed", "Mohamoud", "Mohamud", "Mohn",
    "Moholt", "Moi", "Moksnes", "Moland", "Molde", "Molden", "Moldestad", "Moldskred",
    "Mollan", "Molland", "Møller", "Mollestad", "Molnes", "Molstad", "Molteberg", "Moltu",
    "Molund", "Molvær", "Molvik", "Mong", "Monge", "Mongstad", "Monsen", "Monstad",
    "Moradi", "Mørch", "Mørck", "Mork", "Mørk", "Morken", "Mørkved", "Morland",
    "Mørland", "Mortensen", "Moseng", "Moss", "Mossige", "Mostad", "Mostue", "Moum",
    "Mousa", "Muggerud", "Muhammad", "Muller", "Müller", "Mundal", "Munir", "Munkvold",
    "Munthe", "Munthe-Kaas", "Muren", "Muri", "Musa", "Muse", "Mustafa", "Mydland",
    "Myhr", "Myhra", "Myhre", "Myhren", "Myhrer", "Myhrvold", "Myking", "Mykland",
    "Myklebost", "Myklebust", "Myran", "Myrdal", "Myre", "Myren", "Myrene", "Myreng",
    "Myrhaug", "Myrland", "Myrmel", "Myrseth", "Myrstad", "Myrvang", "Myrvold", "Myrvoll",
    "Naalsund", "Naas", "Nærland", "Nærø", "Næs", "Næss", "Nævdal", "Nagy",
    "Nakken", "Narum", "Narvestad", "Nasir", "Natås", "Natland", "Natvig", "Natvik",
    "Naustdal", "Nawaz", "Nazari", "Nedrebø", "Nedregård", "Nedrelid", "Negård", "Nekstad",
    "Nelson", "Nepstad", "Nerdal", "Nereng", "Nergaard", "Nergård", "Nerheim", "Nerhus",
    "Nerland", "Nerli", "Nervik", "Nes", "Nesbø", "Nese", "Neset", "Nesheim",
    "Nesje", "Nesland", "Ness", "Nessa", "Nesse", "Nesset", "Nesvik", "Neteland",
    "Netland", "Neumann", "Neverdal", "Nevland", "Ngo", "Nguyen", "Nicolaisen", "Nicolaysen",
    "Nielsen", "Nikolaisen", "Nilsen", "Nilssen", "Nilsson", "Nissen", "Nistad", "Njærheim",
    "Nodeland", "Nodland", "Nødland", "Nøkland", "Nøkleby", "Nome", "Noor", "Noori",
    "Norberg", "Nord", "Nordahl", "Nordal", "Nordang", "Nordanger", "Nordås", "Nordberg",
    "Nordbø", "Nordbotten", "Nordby", "Nordeide", "Nordeng", "Nordengen", "Norderhaug", "Nordgaard",
    "Nordgård", "Nordhagen", "Nordhaug", "Nordheim", "Nordhus", "Nordland", "Nordli", "Nordlie",
    "Nordlien", "Nordlund", "Nordmark", "Nordmo", "Nordnes", "Nordrum", "Nordseth", "Nordskag",
    "Nordskog", "Nordstrand", "Nordstrøm", "Nordsveen", "Nordtømme", "Nordtveit", "Nordvik", "Nore",
    "Noreng", "Norheim", "Norland", "Norli", "Norman", "Normann", "Nornes", "Nørstebø",
    "Norum", "Norvik", "Nøttveit", "Nowak", "Nur", "Nuur", "Nybakk", "Nybakken",
    "Nyberg", "Nybø", "Nyborg", "Nybråten", "Nydal", "Nygaard", "Nygard", "Nygård",
    "Nygren", "Nyhagen", "Nyheim", "Nyhus", "Nyhuus", "Nyland", "Nylund", "Nymark",
    "Nymo", "Nymoen", "Nyquist", "Nyrud", "Nysæter", "Nysæther", "Nyseth", "Nystad",
    "Nysted", "Nystrand", "Nystrøm", "Nystuen", "Nysveen", "Nyvold", "Nyvoll", "Obrestad",
    "Odden", "Ødegaard", "Ødegård", "Ødegården", "Odland", "Oen", "Øen", "Ofstad",
    "Oftedal", "Øglænd", "Ohnstad", "Øie", "Øien", "Øiestad", "Øiseth", "Okkenhaug",
    "Økland", "Øksendal", "Oksnes", "Øksnes", "Okstad", "Olafsen", "Olaisen", "Oland",
    "Olaussen", "Olavesen", "Ølberg", "Olden", "Oldervik", "Olesen", "Oliversen", "Ølmheim",
    "Olsen", "Olsnes", "Olsrud", "Olsson", "Olstad", "Olsvik", "Olufsen", "Oma",
    "Omar", "Omdahl", "Omdal", "Omer", "Omholt", "Omland", "Ommedal", "Ommundsen",
    "Onarheim", "Onstad", "Opdahl", "Opdal", "Opedal", "Opgård", "Ophaug", "Opheim",
    "Ophus", "Opland", "Oppedal", "Oppegaard", "Oppegård", "Opsahl", "Opsal", "Opseth",
    "Opstad", "Ørbeck", "Øren", "Ørmen", "Orre", "Orvik", "Os", "Osa",
    "Ose", "Osen", "Oshaug", "Oskarsen", "Osland", "Osman", "Osmani", "Osmundsen",
    "Osnes", "Østberg", "Østbø", "Østby", "Østbye", "Østebø", "Østensen", "Østenstad",
    "Østerås", "Østerbø", "Østerhus", "Østerud", "Østervold", "Østgaard", "Østgård", "Østhus",
    "Østli", "Østlie", "Østlund", "Østmo", "Østrem", "Østreng", "Østvik", "Østvold",
    "Oterhals", "Othman", "Otnes", "Ottem", "Otterlei", "Ottersen", "Otterstad", "Ottesen",
    "Ottestad", "Ottosen", "Overå", "Øverås", "Øverbø", "Øverby", "Øvereng", "Øvergaard",
    "Øvergård", "Øverland", "Øverli", "Overvik", "Ovesen", "Øvland", "Øvrebø", "Øvrelid",
    "Øvretveit", "Øvrevik", "Øvstebø", "Øvstedal", "Øvsthus", "Øwre", "Owren", "Øyan",
    "Øye", "Øyen", "Øygard", "Øygarden", "Øynes", "Øyre", "Paasche", "Palm",
    "Parveen", "Paulsen", "Paulsrud", "Paus", "Pedersen", "Perez", "Persen", "Persson",
    "Petersen", "Petrovic", "Pettersen", "Petterson", "Pettersson", "Pham", "Phan", "Pihl",
    "Pilskog", "Pladsen", "Plassen", "Pleym", "Polden", "Pollestad", "Poulsen", "Prestegård",
    "Presthus", "Prytz", "Qureshi", "Qvale", "Raa", "Raaen", "Raastad", "Rabben",
    "Ræstad", "Rafoss", "Rage", "Rahimi", "Rahman", "Rahmani", "Raja", "Raknes",
    "Rakvåg", "Ramadani", "Ramberg", "Ramfjord", "Ramsdal", "Ramsland", "Ramsøy", "Ramstad",
    "Ramsvik", "Rana", "Randen", "Rånes", "Ranheim", "Ranum", "Rasch", "Rashid",
    "Rasmussen", "Ravn", "Ravnås", "Ravndal", "Raza", "Ree", "Reed", "Refsdal",
    "Refseth", "Refsland", "Refsnes", "Refvik", "Rege", "Rehman", "Reiersen", "Reigstad",
    "Reime", "Rein", "Reinertsen", "Reinholdtsen", "Reistad", "Reitan", "Reite", "Reiten",
    "Rekdal", "Rekkedal", "Rekstad", "Reksten", "Remen", "Remme", "Remmen", "Remøy",
    "Reppe", "Reppen", "Repstad", "Resell", "Ressem", "Revheim", "Reyes", "Rezai",
    "Rian", "Riaz", "Ribe", "Richardsen", "Richter", "Riis", "Riise", "Riiser",
    "Rikardsen", "Rikstad", "Rimstad", "Rindal", "Rinde", "Rinden", "Ring", "Ringdal",
    "Ringen", "Ringheim", "Ringnes", "Ringstad", "Ringvold", "Risa", "Risan", "Risberg",
    "Risdal", "Rise", "Riseth", "Rishaug", "Risnes", "Risøy", "Rist", "Risvik",
    "Roald", "Robberstad", "Roberg", "Røberg", "Roberts", "Robertsen", "Robinson", "Robstad",
    "Rød", "Rodal", "Rødal", "Rode", "Rødland", "Rodriguez", "Rødsand", "Rødseth",
    "Rødsjø", "Røe", "Røed", "Roen", "Røen", "Røgeberg", "Rognan", "Rogne",
    "Rognerud", "Rognes", "Rognli", "Rognlien", "Rognmo", "Rognstad", "Rogstad", "Rohde",
    "Røhne", "Røine", "Røise", "Røisland", "Røkenes", "Røkke", "Rokne", "Rokstad",
    "Roksvåg", "Roland", "Rolfsen", "Rolfsnes", "Rolland", "Rolstad", "Rom", "Rømo",
    "Romsdal", "Røneid", "Rong", "Rongved", "Rønhovde", "Rønne", "Rønneberg", "Rønnestad",
    "Rønning", "Rønningen", "Roos", "Røren", "Rørstad", "Rørtveit", "Rørvik", "Røsand",
    "Rosenberg", "Rosenlund", "Rosenvinge", "Rosland", "Rosnes", "Ross", "Rossebø", "Rosseland",
    "Rossland", "Røssland", "Røst", "Rostad", "Røstad", "Røste", "Røsten", "Røsvik",
    "Rosvold", "Rosvoll", "Rotevatn", "Roth", "Røv", "Rovik", "Røvik", "Røyland",
    "Røyrvik", "Røyset", "Røysland", "Rud", "Rudi", "Rudolfsen", "Rue", "Rugland",
    "Rui", "Runde", "Rustad", "Rustand", "Rusten", "Ruud", "Ryan", "Rydland",
    "Rydningen", "Rye", "Ryen", "Ryeng", "Rygg", "Rygh", "Rykkje", "Ryland",
    "Rynning", "Rystad", "Saastad", "Sæbø", "Saeed", "Sæland", "Sæle", "Sælen",
    "Sæter", "Sæterbø", "Sæterdal", "Sætermo", "Sæternes", "Sæther", "Sæthre", "Sætra",
    "Sætran", "Sætre", "Sætren", "Sævareid", "Sæverud", "Sævik", "Safi", "Saga",
    "Sagbakken", "Sagen", "Sagmo", "Sagstad", "Sagstuen", "Said", "Sakariassen", "Sakshaug",
    "Salah", "Salamonsen", "Salberg", "Salbu", "Saleem", "Saleh", "Salih", "Salim",
    "Salimi", "Salomonsen", "Salte", "Saltnes", "Salvesen", "Samdal", "Samnøy", "Samuelsen",
    "Sand", "Sandaker", "Sandal", "Sandanger", "Sandbæk", "Sandbakk", "Sandbakken", "Sandberg",
    "Sande", "Sanden", "Sander", "Sandersen", "Sandhåland", "Sandland", "Sandli", "Sandmo",
    "Sandnes", "Sandø", "Sandøy", "Sandsmark", "Sandstad", "Sandtorv", "Sandum", "Sandvær",
    "Sandve", "Sandven", "Sandvik", "Sandvold", "Sandvoll", "Sangolt", "Sanne", "Sannerud",
    "Sannes", "Santos", "Sara", "Sarwar", "Saue", "Saur", "Schanche", "Schanke",
    "Schau", "Schei", "Scheie", "Schie", "Schjelderup", "Schjerven", "Schjetne", "Schjølberg",
    "Schmidt", "Schneider", "Schou", "Schøyen", "Schrøder", "Schultz", "Schulz", "Scott",
    "Seeberg", "Seglem", "Seierstad", "Seim", "Sekkingstad", "Sekse", "Seland", "Seldal",
    "Sele", "Seljeseth", "Sellæg", "Selle", "Sellevold", "Selmer", "Selnes", "Selstad",
    "Selvåg", "Selvik", "Sem", "Semb", "Seppola", "Serigstad", "Sevaldsen", "Severinsen",
    "Shah", "Shahzad", "Shala", "Sharif", "Sharifi", "Sharma", "Sheikh", "Shevchenko",
    "Shinwari", "Shrestha", "Sigurdsen", "Sigvartsen", "Sikveland", "Silden", "Silseth", "Silva",
    "Simensen", "Simon", "Simonsen", "Singh", "Singstad", "Sinnes", "Siqveland", "Sirevåg",
    "Sirnes", "Sivertsen", "Sjaastad", "Sjåstad", "Sjåvik", "Sjo", "Sjøberg", "Sjøblom",
    "Sjøen", "Sjøgren", "Sjøli", "Sjølie", "Sjøstrøm", "Sjøthun", "Sjøvold", "Sjøvoll",
    "Sjursen", "Skaar", "Skaare", "Skadberg", "Skage", "Skagen", "Skagestad", "Skailand",
    "Skåland", "Skålevik", "Skansen", "Skar", "Skår", "Skarbø", "Skårdal", "Skare",
    "Skåre", "Skaret", "Skårland", "Skarshaug", "Skarstad", "Skarstein", "Skarsvåg", "Skau",
    "Skauen", "Skaug", "Skauge", "Skaugen", "Skavhaug", "Skei", "Skeide", "Skeie",
    "Skevik", "Skiaker", "Skille", "Skinnes", "Skinstad", "Skistad", "Skjæret", "Skjærstad",
    "Skjærvik", "Skjæveland", "Skjeggestad", "Skjelbred", "Skjelstad", "Skjelvik", "Skjerdal", "Skjerping",
    "Skjerve", "Skjerven", "Skjervheim", "Skjervold", "Skjetne", "Skjevik", "Skjølberg", "Skjold",
    "Skjolden", "Skjønberg", "Skjong", "Skjønhaug", "Skjørestad", "Skog", "Skoge", "Skogen",
    "Skogheim", "Skogland", "Skogli", "Skoglund", "Skogly", "Skogmo", "Skogseth", "Skogsrud",
    "Skogstad", "Skogvold", "Skogvoll", "Skøien", "Skomedal", "Skorpen", "Skorstad", "Skotnes",
    "Skotte", "Skovly", "Skram", "Skråmestø", "Skramstad", "Skrede", "Skretteberg", "Skretting",
    "Skrettingland", "Skuland", "Skullerud", "Skulstad", "Skurdal", "Skutle", "Slåen", "Slåtten",
    "Sleire", "Sletner", "Sletta", "Slette", "Slettebø", "Slettedal", "Slettemark", "Sletten",
    "Slettum", "Sletvold", "Sleveland", "Slinning", "Slyngstad", "Smeby", "Smedsrud", "Smedstad",
    "Smeland", "Smestad", "Smistad", "Smith", "Smørdal", "Sneve", "Søberg", "Søbstad",
    "Sødal", "Søderholm", "Søfteland", "Søgaard", "Søgård", "Sogn", "Søiland", "Sola",
    "Solås", "Solbakk", "Solbakken", "Solberg", "Solbu", "Soldal", "Solem", "Soleng",
    "Solevåg", "Solgård", "Solhaug", "Solheim", "Solli", "Sollid", "Sollie", "Sollien",
    "Solomon", "Solstad", "Solstrand", "Solsvik", "Soltvedt", "Soltveit", "Solum", "Solvang",
    "Sølvberg", "Solvik", "Solvoll", "Soma", "Somby", "Sømme", "Sommer", "Sommerseth",
    "Sommerstad", "Sommervold", "Sønderland", "Sønstebø", "Sønsteby", "Sønsterud", "Sørbø", "Sørby",
    "Sørdal", "Søreide", "Søreng", "Sørensen", "Sørgård", "Sørhaug", "Sørheim", "Sørhus",
    "Sørland", "Sørli", "Sørlie", "Sørmo", "Sørnes", "Sortland", "Sørum", "Sørvik",
    "Søvik", "Søyland", "Sparby", "Sperre", "Spilde", "Sporsheim", "Stabell", "Stadheim",
    "Staff", "Stålesen", "Stalsberg", "Stamnes", "Standal", "Stang", "Stange", "Stangeland",
    "Starheim", "Stav", "Stava", "Stave", "Stavem", "Staven", "Stavenes", "Stavik",
    "Stavland", "Stavnes", "Stavrum", "Steen", "Steffensen", "Stein", "Steindal", "Steine",
    "Steinnes", "Steinsland", "Steinsvik", "Steiro", "Stenberg", "Stendal", "Stene", "Stenersen",
    "Stenerud", "Stenhaug", "Stensby", "Stensen", "Stenseth", "Stensland", "Stensrud", "Stenstad",
    "Stensvold", "Stenvik", "Stephansen", "Stiansen", "Stien", "Stigen", "Stjern", "Støa",
    "Støen", "Stokka", "Stokkan", "Stokke", "Stokkeland", "Stokken", "Stokkenes", "Stokland",
    "Stokstad", "Stølan", "Støle", "Stølen", "Stoltenberg", "Storaker", "Storås", "Stordahl",
    "Stordal", "Størdal", "Storebø", "Storeide", "Storesund", "Storhaug", "Storheim", "Størkersen",
    "Størksen", "Storli", "Storm", "Stormark", "Stormo", "Stormoen", "Stormyr", "Stornes",
    "Storøy", "Storrø", "Størseth", "Storsve", "Storsveen", "Storvik", "Støylen", "Strand",
    "Strandberg", "Strande", "Stranden", "Strandheim", "Straume", "Stray", "Strøm", "Strømberg",
    "Strømland", "Strømme", "Strømmen", "Strømnes", "Strømsnes", "Strømstad", "Strømsvåg", "Stubberud",
    "Stuen", "Sture", "Styve", "Suhr", "Sulaiman", "Suleiman", "Sulen", "Sumstad",
    "Sund", "Sundal", "Sundberg", "Sundby", "Sunde", "Sundet", "Sundfær", "Sundgot",
    "Sundland", "Sundli", "Sundnes", "Sundseth", "Sundstrøm", "Sundt", "Surdal", "Sværen",
    "Svanberg", "Svanes", "Svanevik", "Svardal", "Svarstad", "Sveberg", "Svee", "Sveen",
    "Svela", "Svellingen", "Svendsen", "Svendsrud", "Svenkerud", "Svenning", "Svenningsen", "Svensen",
    "Svensli", "Svensson", "Sverdrup", "Sveum", "Sviggum", "Svihus", "Sviland", "Svindland",
    "Svingen", "Syed", "Sylta", "Sylte", "Synnes", "Synnevåg", "Syrstad", "Systad",
    "Syversen", "Syvertsen", "Tafjord", "Taha", "Tahir", "Takle", "Taksdal", "Takvam",
    "Talberg", "Tallaksen", "Tandberg", "Tande", "Tandstad", "Tang", "Tangen", "Tangstad",
    "Taraldsen", "Taranger", "Tariq", "Taule", "Taylor", "Teien", "Teig", "Teige",
    "Teigen", "Teigland", "Tekeste", "Tekie", "Tekle", "Telle", "Tellefsen", "Tengesdal",
    "Tennfjord", "Tenold", "Terjesen", "Tesdal", "Tesfamariam", "Tesfamichael", "Tesfay", "Tessem",
    "Tetlie", "Tewelde", "Tharaldsen", "Theodorsen", "Thingstad", "Thoen", "Thøgersen", "Thomas",
    "Thomassen", "Thommesen", "Thompson", "Thomsen", "Thon", "Thorbjørnsen", "Thoresen", "Thorgersen",
    "Thorkildsen", "Thorsen", "Thorshaug", "Thorsø", "Thorsrud", "Thorstensen", "Thorud", "Thorvaldsen",
    "Thrane", "Throndsen", "Thu", "Thue", "Thuen", "Thune", "Thunes", "Thygesen",
    "Tidemann", "Tiller", "Titlestad", "Tjelle", "Tjelta", "Tjemsland", "Tjessem", "Tjore",
    "Tjørhom", "Tjøstheim", "Tjøsvoll", "Tjøtta", "Tkachenko", "Tobiassen", "Todal", "Todnem",
    "Toft", "Tofte", "Tokerud", "Tokle", "Tollaksen", "Tollefsen", "Tøllefsen", "Tolo",
    "Tømmerås", "Tømmervik", "Tomren", "Tømte", "Tomter", "Tøndel", "Tønder", "Tonheim",
    "Tønnesen", "Tønnessen", "Tonning", "Tønsberg", "Tonstad", "Torbergsen", "Torbjørnsen", "Toresen",
    "Torgersen", "Torheim", "Torjussen", "Torkelsen", "Torkildsen", "Torland", "Tornes", "Torp",
    "Torset", "Torsteinsen", "Torstensen", "Torsvik", "Torvik", "Torvund", "Tøsse", "Totland",
    "Toverud", "Træet", "Tran", "Trana", "Trengereid", "Trinh", "Trøan", "Trøen",
    "Trondsen", "Trones", "Trønnes", "Tronrud", "Tronstad", "Trulsen", "Truong", "Trydal",
    "Tryggestad", "Tsegay", "Tuft", "Tufte", "Tufteland", "Tungland", "Tunheim", "Turøy",
    "Tvedt", "Tvedten", "Tveit", "Tveita", "Tveitan", "Tveite", "Tveiten", "Tveito",
    "Tvenge", "Tverå", "Tverberg", "Tvete", "Tveten", "Tveter", "Tyldum", "Tysnes",
    "Tysse", "Ueland", "Ugelstad", "Ugland", "Ulland", "Ulleberg", "Ullestad", "Ulriksen",
    "Ulset", "Ulseth", "Ulstein", "Ulven", "Ulvestad", "Ulvik", "Ulvin", "Ulvund",
    "Underhaug", "Undheim", "Undrum", "Unhjem", "Unneland", "Urdal", "Urke", "Ursin",
    "Urstad", "Usman", "Ustad", "Utgård", "Uthaug", "Utheim", "Uthus", "Utne",
    "Utnes", "Utsi", "Utvik", "Vaa", "Vaage", "Vabø", "Vadseth", "Værnes",
    "Våga", "Våge", "Vågen", "Vågenes", "Vagle", "Vaksdal", "Valberg", "Valde",
    "Valderhaug", "Valen", "Valla", "Valland", "Valle", "Vallestad", "Valø", "Valseth",
    "Valstad", "Valvik", "Vang", "Vangen", "Vangsnes", "Vanvik", "Vårdal", "Varhaug",
    "Vartdal", "Vassbotn", "Vassdal", "Vatland", "Vatle", "Vatn", "Vatne", "Vea",
    "Vedå", "Vedal", "Vedøy", "Vedvik", "Vegsund", "Veiby", "Veivåg", "Veland",
    "Velde", "Velle", "Venås", "Vervik", "Vestad", "Vestbø", "Vestbøstad", "Vestby",
    "Vestli", "Vestly", "Vestnes", "Vestøl", "Vestre", "Vestrheim", "Vestvik", "Vetrhus",
    "Veum", "Vevang", "Vevle", "Viddal", "Vie", "Vigdal", "Vigre", "Vigrestad",
    "Vik", "Vika", "Vikan", "Vikane", "Vikanes", "Vike", "Viken", "Vikene",
    "Vikøren", "Vikse", "Vilhelmsen", "Villanger", "Vindenes", "Vinje", "Visnes", "Vist",
    "Viste", "Vistnes", "Vo", "Vogt", "Vold", "Volden", "Voldsund", "Voll",
    "Vollan", "Volle", "Vollen", "Vonheim", "Vorland", "Vu", "Waage", "Waaler",
    "Wærnes", "Wagner", "Wahl", "Wahlberg", "Wahlstrøm", "Walberg", "Walde", "Waldeland",
    "Walderhaug", "Walker", "Walle", "Wallin", "Walseth", "Walstad", "Wang", "Wangberg",
    "Wangen", "Wanvik", "Warholm", "Warsame", "Wathne", "Weber", "Weberg", "Wehus",
    "Weiseth", "Welde", "Welle", "Wennberg", "Wergeland", "Werner", "Wessel", "Westad",
    "Westberg", "Westby", "Westbye", "Westerheim", "Westerlund", "Westgaard", "Westgård", "Westlie",
    "Westrum", "Wetteland", "Weum", "White", "Wibe", "Wiborg", "Wickstrøm", "Widding",
    "Wie", "Wien", "Wiggen", "Wiig", "Wiik", "Wik", "Wiken", "Wiker",
    "Wiklund", "Wikstrøm", "Wilberg", "Wilhelmsen", "Willassen", "Wille", "Williams", "Willumsen",
    "Wilson", "Winge", "Winger", "Winje", "Winsnes", "Winther", "Wisløff", "Wisniewski",
    "Wist", "Wisth", "With", "Wøien", "Wojcik", "Wold", "Wolden", "Woldseth",
    "Wolff", "Woll", "Wollan", "Wong", "Worren", "Wozniak", "Wright", "Wroldsen",
    "Wu", "Wulff", "Xu", "Yang", "Yasin", "Yemane", "Yildirim", "Yildiz",
    "Yilmaz", "Yndestad", "Yohannes", "Young", "Yousef", "Yri", "Ytreland", "Ytterstad",
    "Yttervik", "Yu", "Yusuf", "Zachariassen", "Zahl", "Zakariassen", "Zaman", "Zhang",
    "Zielinski", "Zimmermann",
})

NORWEGIAN_NAMES: frozenset = NORWEGIAN_FEMALE_NAMES | NORWEGIAN_MALE_NAMES | NORWEGIAN_SURNAMES


# ── Common Norwegian words that are NOT person names ─────────────────────────
# Used to suppress NER false positives. Organised by part of speech / domain.

NORWEGIAN_COMMON_WORDS: frozenset = frozenset({
    # ── Determiners / pronouns / articles ────────────────────────────────────
    "den", "det", "de", "ei", "en", "et", "ett",
    "han", "hun", "vi", "dere", "dem", "seg",
    "denne", "dette", "disse", "noen", "noe", "alle", "begge",
    "hvert", "hver", "ingen", "enhver", "man", "meg", "deg", "oss",

    # ── Common prepositions / conjunctions / adverbs ──────────────────────────
    "av", "fra", "til", "for", "med", "uten", "ved", "på", "i", "om",
    "etter", "over", "under", "mellom", "mot", "gjennom", "langs",
    "innen", "inntil", "ifølge", "henhold", "vedrørende",
    "og", "eller", "men", "samt", "både", "enten",
    "fordi", "siden", "når", "hvis", "dersom", "selv",
    "ikke", "også", "bare", "kun", "alt", "allerede",
    "her", "der", "nå", "da", "så", "som", "at", "jo", "vel",
    "ellers", "imidlertid", "likevel", "dessuten", "derfor", "deretter",
    "herved", "hermed", "derimot", "eksplisitt", "henholdsvis",

    # ── Common verbs (as sentence starters or nominalised) ───────────────────
    "er", "var", "blir", "ble", "har", "hadde", "kan", "kunne",
    "vil", "ville", "skal", "skulle", "må", "måtte", "bør", "burde",
    "ser", "ser", "gir", "tar", "gjør", "sier", "kommer", "går",
    "har", "får", "vet", "tror", "mener", "ønsker",
    "utbedres", "justeres", "tilsier", "forutsetter", "innebærer",
    "medfølger", "foreligger", "gjelder", "fremgår", "viser",

    # ── Common nouns – general ────────────────────────────────────────────────
    "hus", "bil", "vei", "gate", "sted", "tid", "dag", "uke", "år",
    "måned", "time", "mann", "dame", "person", "folk", "barn",
    "familie", "arbeid", "jobb", "penger", "mat", "vann", "luft",
    "bok", "brev", "sak", "del", "form", "side", "type", "art",
    "nivå", "grad", "verdi", "antall", "andel", "område", "felt",
    "punkt", "linje", "felt", "gruppe", "lag", "plan", "system",
    "løsning", "mulighet", "behov", "krav", "rett", "plikt",
    "ansvar", "risiko", "kostnad", "pris", "avgift", "skatt",
    "kontrakt", "avtale", "søknad", "klage", "rapport",

    # ── Common nouns – neighbourhood / surroundings ───────────────────────────
    "skole", "barnehage", "butikk", "busstopp", "buss", "tog", "trikk",
    "sentrum", "nærhet", "nabo", "gård", "gate", "park", "plass",
    "kirke", "sykehus", "legesenter", "apotek", "bibliotek", "kino",
    "restaurant", "kafé", "idrettshall", "svømmehall",

    # ── Common adjectives ─────────────────────────────────────────────────────
    "ny", "nytt", "nye", "gammel", "gammelt", "gamle",
    "stor", "stort", "store", "liten", "lite", "små",
    "god", "godt", "gode", "dårlig", "dårlige",
    "lang", "kort", "høy", "lav", "bred", "smal", "dyp",
    "åpen", "lukket", "privat", "offentlig", "felles",
    "norsk", "norske", "utenlandsk", "lokal", "regional", "nasjonal",
    "viktig", "nødvendig", "riktig", "feil", "enkel", "vanskelig",
    "naturlig", "praktisk", "teknisk", "juridisk", "økonomisk",
    "første", "andre", "tredje", "fjerde", "siste", "neste",
    "hele", "halv", "tom", "full", "egen", "annen", "samme",
    "isolert", "integrert", "asfaltert", "automatisk", "innkludert",
    "vedlagte", "følgende", "gjeldende", "overnevnte", "nevnte",
    "skrånende", "terrassert", "opparbeidet",

    # ── Common numerals / quantities ─────────────────────────────────────────
    "én", "ett", "to", "tre", "fire", "fem", "seks", "syv", "åtte", "ni", "ti",
    "første", "andre", "tredje",

    # ── Greetings / discourse markers ────────────────────────────────────────
    "velkommen", "hei", "takk", "vennligst", "obs", "merk", "nb",
    "ps", "dvs", "osv", "jf", "ref", "se", "les",

    # ── Organisational / document terms ──────────────────────────────────────
    "forutsetning", "forutsetninger", "opplysning", "opplysninger",
    "vedlegg", "dokument", "skjema", "signatur", "dato",
    "paragraf", "kapittel", "avsnitt", "punkt", "pkt",
    "tilstandsrapport", "tilstandsanalyse", "tilstandsgrader",
    "tilstandsgradene", "byggemåte", "byggeår",

    # ── Real estate / property terms (supplement to engine.py denylist) ──────
    "eierleilighet", "selveierleilighet", "andelsbolig",
    "fellesareal", "fellesarealer", "fellesgjeld", "felleskostnader",
    "tomteforhold", "terrengforhold", "fuktsikring",
    "etasjeskille", "etasjeskiller", "takkonstruksjon", "veggkonstruksjon",
    "bygningsdeler", "innkjørsel", "garasjeport", "boddør",
    "betonggulv", "portåpner", "referansenivå", "tilstandsvurdert",
    # Inflected / compound forms not caught by the suffix regex
    "inn", "innvendige", "sluk", "kassett", "overgang",
    "boplikt", "boplikten", "planen", "boder",
    "prisantydning", "prisantydningen",
    "attraktiv", "attraktivt", "attraktive",
    "anvendelse", "anvendelsen",
    "oppdragsnr", "oppdragsnummer",
    "vinskap", "vinkapet",
    "bruksendring", "bruksendringer",
    "boligkjøperforsikring", "markedsavtale",
    "reguleringsplankart", "kommuneplankart",
    "eiendomsforvaltning", "forbrukerrådet",
    "kommunalinformasjon", "forbrukerinformasjon",
    "teodolitt", "lengde", "drenering", "dreneringen",
    "adkomstveranda", "adkomsten",
    "lekestativ", "lekeplassen", "planter",
    # Building elements / materials
    "membran", "membranen", "membraner",
    "forholdet", "forholdene",
    # Verbs incorrectly tagged
    "levere", "leverer", "levert",
    # Cadastral / property reference abbreviations
    "gnr", "bnr", "snr",
    # Norwegian direction/position adjectives
    "øvre", "nedre", "vestre", "østre", "nordre", "søndre",

    # ── Days of week / months (NER sometimes tags these) ─────────────────────
    "mandag", "tirsdag", "onsdag", "torsdag", "fredag", "lørdag", "søndag",
    "januar", "februar", "mars", "april", "mai", "juni",
    "juli", "august", "september", "oktober", "november", "desember",
})
